CREATE TABLE [dbo].[Applications] (
    [ID]                           BIGINT          IDENTITY (1, 1) NOT NULL,
    [AccessAdminUser]              NVARCHAR (250)  NULL,
    [AccessManageLevel]            NVARCHAR (MAX)  NULL,
    [AllocatedSeats]               INT             NULL,
    [ApprovalTypeChoice]           NVARCHAR (MAX)  NULL,
    [ApproverUser]                 NVARCHAR (250)  NULL,
    [BuildNumber]                  NVARCHAR (250)  NULL,
    [BusinessManagerUser]          NVARCHAR (MAX)  NULL,
    [CategoryNameChoice]           NVARCHAR (250)  NULL,
    [Closed]                       BIT             NULL,
    [CloseDate]                    DATETIME        NULL,
    [Comment]                      NVARCHAR (MAX)  NULL,
    [CreationDate]                 DATETIME        NULL,
    [CurrentStageStartDate]        DATETIME        NULL,
    [DepartmentLookup]             BIGINT          NULL,
    [Description]                  NVARCHAR (MAX)  NULL,
    [DocumentLibraryName]          NVARCHAR (250)  NULL,
    [FunctionalAreaLookup]         BIGINT          NULL,
    [History]                      NVARCHAR (MAX)  NULL,
    [InitiatorUser]                NVARCHAR (MAX)  NULL,
    [IssueTypeOptions]             NVARCHAR (MAX)  NULL,
    [ModuleStepLookup]             NVARCHAR (250)  NULL,
    [NumberOfSeats]                INT             NULL,
    [OnHold]                       INT             NULL,
    [OwnerUser]                    NVARCHAR (250)  NULL,
    [RequestTypeLookup]            BIGINT          NULL,
    [SoftwareKey]                  NVARCHAR (250)  NULL,
    [SoftwareMajorVersion]         NVARCHAR (250)  NULL,
    [SoftwareMinorVersion]         NVARCHAR (250)  NULL,
    [SoftwarePatchRevision]        NVARCHAR (250)  NULL,
    [SoftwareVersion]              NVARCHAR (250)  NULL,
    [StageActionUsersUser]         NVARCHAR (250)  NULL,
    [StageActionUserTypes]         NVARCHAR (250)  NULL,
    [StageStep]                    INT             NULL,
    [Status]                       NVARCHAR (250)  NULL,
    [SubCategory]                  NVARCHAR (250)  NULL,
    [SupportedByUser]              NVARCHAR (250)  NULL,
    [SyncAtModuleLevel]            BIT             NULL,
    [SyncToRequestType]            BIT             NULL,
    [TicketId]                     NVARCHAR (250)  NULL,
    [VendorName]                   NVARCHAR (250)  NULL,
    [WorkflowSkipStages]           NVARCHAR (250)  NULL,
    [Title]                        VARCHAR (250)   NULL,
    [LicenseBasisChoice]           NVARCHAR (250)  NULL,
    [NumLicensesTotal]             INT             NULL,
    [NumLicensesTotalNotes]        NVARCHAR (250)  NULL,
    [NumUsers]                     INT             NULL,
    [HostingTypeChoice]            NVARCHAR (250)  NULL,
    [VendorLookup]                 BIGINT          NULL,
    [InProductionSince]            NVARCHAR (250)  NULL,
    [FrequencyOfUpgradesChoice]    NVARCHAR (250)  NULL,
    [FrequencyOfTypicalUse]        NVARCHAR (250)  NULL,
    [FrequencyOfUpgradesNotes]     NVARCHAR (250)  NULL,
    [NextPlannedMajorUpgrade]      NVARCHAR (500)  NULL,
    [VersionInstalled]             NVARCHAR (250)  NULL,
    [VersionLatestRelease]         NVARCHAR (250)  NULL,
    [TenantID]                     NVARCHAR (128)  NULL,
    [DataEditors]                  NVARCHAR (250)  DEFAULT ('') NULL,
    [Created]                      DATETIME        DEFAULT (getdate()) NOT NULL,
    [Modified]                     DATETIME        DEFAULT (getdate()) NOT NULL,
    [CreatedByUser]                NVARCHAR (128)  DEFAULT ('00000000-0000-0000-0000-000000000000') NOT NULL,
    [ModifiedByUser]               NVARCHAR (128)  DEFAULT ('00000000-0000-0000-0000-000000000000') NOT NULL,
    [Deleted]                      BIT             DEFAULT ((0)) NULL,
    [Attachments]                  NVARCHAR (2000) DEFAULT ('') NULL,
    [ResolutionDate]               DATETIME        NULL,
    [CustomUGChoice01]             NVARCHAR (MAX)  NULL,
    [CustomUGChoice02]             NVARCHAR (MAX)  NULL,
    [CustomUGChoice03]             NVARCHAR (MAX)  NULL,
    [CustomUGChoice04]             NVARCHAR (MAX)  NULL,
    [CustomUGDate01]               DATETIME        NULL,
    [CustomUGDate02]               DATETIME        NULL,
    [CustomUGDate03]               DATETIME        NULL,
    [CustomUGDate04]               DATETIME        NULL,
    [CustomUGText01]               NVARCHAR (250)  NULL,
    [CustomUGText02]               NVARCHAR (250)  NULL,
    [CustomUGText03]               NVARCHAR (250)  NULL,
    [CustomUGText04]               NVARCHAR (250)  NULL,
    [CustomUGText05]               NVARCHAR (250)  NULL,
    [CustomUGText06]               NVARCHAR (250)  NULL,
    [CustomUGText07]               NVARCHAR (250)  NULL,
    [CustomUGText08]               NVARCHAR (250)  NULL,
    [CustomUGUser01]               NVARCHAR (MAX)  NULL,
    [CustomUGUser02]               NVARCHAR (MAX)  NULL,
    [CustomUGUser03]               NVARCHAR (MAX)  NULL,
    [CustomUGUser04]               NVARCHAR (MAX)  NULL,
    [CustomUGUserMulti01]          NVARCHAR (250)  NULL,
    [CustomUGUserMulti02]          NVARCHAR (250)  NULL,
    [CustomUGUserMulti03]          NVARCHAR (250)  NULL,
    [CustomUGUserMulti04]          NVARCHAR (250)  NULL,
    [MaintenanceWindowStart]       NVARCHAR (250)  NULL,
    [MaintenanceWindowEnd]         NVARCHAR (250)  NULL,
    [SLADisabled]                  BIT             DEFAULT ((0)) NULL,
    [AssignedBy]                   NVARCHAR (128)  DEFAULT ('00000000-0000-0000-0000-000000000000') NULL,
    [ApplicationTier]              NVARCHAR (250)  NULL,
    [ApplicationType]              NVARCHAR (250)  NULL,
    [IsPDSA]                       BIT             DEFAULT ((0)) NULL,
    [IsProductApp]                 BIT             DEFAULT ((0)) NULL,
    [InteractsWithMSOffice]        BIT             DEFAULT ((0)) NULL,
    [ContainsPI]                   BIT             DEFAULT ((0)) NULL,
    [OnSB272List]                  BIT             DEFAULT ((0)) NULL,
    [OnICD10List]                  BIT             DEFAULT ((0)) NULL,
    [SystemPurpose]                NVARCHAR (MAX)  NULL,
    [SponsorsUser]                 NVARCHAR (128)  DEFAULT ('00000000-0000-0000-0000-000000000000') NULL,
    [BusinessFunction]             NVARCHAR (250)  NULL,
    [ResolvedByUser]               NVARCHAR (128)  DEFAULT ('00000000-0000-0000-0000-000000000000') NULL,
    [ClosedByUser]                 NVARCHAR (128)  DEFAULT ('00000000-0000-0000-0000-000000000000') NULL,
    [UsesADAuthentication]         BIT             DEFAULT ((0)) NULL,
    [Complexity]                   NVARCHAR (250)  NULL,
    [PriorityLookup]               BIGINT          NULL,
    [Platform]                     NVARCHAR (250)  NULL,
    [ClientUIPlatform]             NVARCHAR (250)  NULL,
    [DBType]                       NVARCHAR (250)  NULL,
    [InstallLocation]              NVARCHAR (250)  NULL,
    [Availability]                 NVARCHAR (250)  NULL,
    [NumUserNotes]                 NVARCHAR (250)  NULL,
    [UserType]                     NVARCHAR (250)  NULL,
    [ComplianceNotes]              NVARCHAR (MAX)  NULL,
    [ProgrammingLanguage]          NVARCHAR (250)  NULL,
    [InterfacesOutgoing]           NVARCHAR (MAX)  NULL,
    [InterfacesIncoming]           NVARCHAR (MAX)  NULL,
    [PlannedActivities]            NVARCHAR (MAX)  NULL,
    [EOLTarget]                    NVARCHAR (250)  NULL,
    [BusinessUsage]                NVARCHAR (250)  NULL,
    [ExternalAppName]              NVARCHAR (250)  NULL,
    [VersionInstalledDate]         DATETIME        NULL,
    [ExternalBusinessPartners]     NVARCHAR (MAX)  NULL,
    [ExternalUsers]                BIT             DEFAULT ((0)) NULL,
    [ExternalUsersLoginRequired]   BIT             DEFAULT ((0)) NULL,
    [BusinessImpact]               NVARCHAR (250)  NULL,
    [ContractStatus]               NVARCHAR (250)  NULL,
    [FrontEndTechnology]           NVARCHAR (250)  NULL,
    [BackEndTechnology]            NVARCHAR (250)  NULL,
    [MiddlewareTechnology]         NVARCHAR (250)  NULL,
    [FileSystem]                   NVARCHAR (250)  NULL,
    [ConfigurationDataLocation]    NVARCHAR (250)  NULL,
    [ClientSoftware]               NVARCHAR (250)  NULL,
    [CreatesCookies]               NVARCHAR (250)  NULL,
    [UsesHTMLStorage]              NVARCHAR (250)  NULL,
    [AdminAccount]                 NVARCHAR (250)  NULL,
    [BackEndAccess]                NVARCHAR (250)  NULL,
    [FrontEndAccess]               NVARCHAR (250)  NULL,
    [OtherAccess]                  NVARCHAR (250)  NULL,
    [LicenseExpiratonDate]         DATETIME        NULL,
    [InternalProcurementContact]   NVARCHAR (250)  NULL,
    [UserRange]                    NVARCHAR (250)  NULL,
    [AccessType]                   NVARCHAR (250)  NULL,
    [TouchPointsType]              NVARCHAR (250)  NULL,
    [TechnologyComplexity]         NVARCHAR (250)  NULL,
    [TechnologyMaturity]           NVARCHAR (250)  NULL,
    [ScheduleRisk]                 NVARCHAR (50)   NULL,
    [FinancialImpact]              NVARCHAR (250)  NULL,
    [BusinessAdoptionRisk]         NVARCHAR (250)  NULL,
    [ImpactsRevenue]               VARCHAR (250)   NULL,
    [ImpactOnUsers]                NVARCHAR (250)  NULL,
    [SecurityAndCompliance]        NVARCHAR (250)  NULL,
    [AcceptableLeadTimeToFix]      NVARCHAR (250)  NULL,
    [ComplexityScore]              INT             NULL,
    [RiskScore]                    INT             NULL,
    [BusinessImpactScore]          INT             NULL,
    [ComplexityClassification]     NVARCHAR (250)  NULL,
    [RiskBusinessImpactClass]      NVARCHAR (250)  NULL,
    [ApplicationRedundancy]        NVARCHAR (250)  NULL,
    [ApplicationImportance]        NVARCHAR (250)  NULL,
    [ApplicationPrivacy]           NVARCHAR (250)  NULL,
    [InProductionDate]             DATETIME        NULL,
    [MaintenanceContractStartDate] DATETIME        NULL,
    [MaintenanceContractEndDate]   DATETIME        NULL,
    [NextUpgradeDate]              DATETIME        NULL,
    [InterfacesIncomingApps]       NVARCHAR (250)  NULL,
    [InterfacesOutgoingApps]       NVARCHAR (250)  NULL,
    [TicketBusinessManager2User]   NVARCHAR (128)  NULL,
    [TicketOwner2]                 NVARCHAR (128)  NULL,
    [SupportedBy2]                 NVARCHAR (128)  NULL,
    [AppTypeRating]                NVARCHAR (250)  NULL,
    [LatestVersionReleaseDate]     DATETIME        NULL,
    [ExtendedSupportEndDate]       DATETIME        NULL,
    [EndOfLifeDate]                DATETIME        NULL,
    [Integrity]                    NVARCHAR (250)  NULL,
    [RecoveryTimeObjective]        NVARCHAR (250)  NULL,
    [RecoveryPointObjective]       NVARCHAR (250)  NULL,
    [SupportedBusinessProcesses]   NVARCHAR (MAX)  NULL,
    [Standard]                     NVARCHAR (128)  NULL,
    [StandardReviewDate]           DATETIME        NULL,
    [NextStandardReviewDate]       DATETIME        NULL,
    [AuthenticationTypes]          NVARCHAR (50)   NULL,
    [AuthenticationMechanisms]     NVARCHAR (50)   NULL,
    [UserAuthInterfaces]           NVARCHAR (50)   NULL,
    [SSOTypes]                     NVARCHAR (50)   NULL,
    [ApprovalDate] DATETIME NULL, 
    [ApprovedByUser] VARCHAR(128) NULL, 
    PRIMARY KEY CLUSTERED ([ID] ASC),
    FOREIGN KEY ([DepartmentLookup]) REFERENCES [dbo].[Department] ([ID]),
    FOREIGN KEY ([FunctionalAreaLookup]) REFERENCES [dbo].[FunctionalAreas] ([ID]),
    FOREIGN KEY ([RequestTypeLookup]) REFERENCES [dbo].[Config_Module_RequestType] ([ID])
);














GO

GO

GO
CREATE NONCLUSTERED INDEX [IX_Applications_ModuleStepLookup] ON [dbo].[Applications] ([ModuleStepLookup])

GO
CREATE NONCLUSTERED INDEX [IX_Applications_Status] ON [dbo].[Applications] ([Status])

GO
CREATE NONCLUSTERED INDEX [IX_Applications_TicketId] ON [dbo].[Applications] ([TicketId])

GO
CREATE NONCLUSTERED INDEX [IX_Applications_VendorName] ON [dbo].[Applications] ([VendorName])