CREATE TABLE [dbo].[Config_Modules] (
    [ID]                              BIGINT          IDENTITY (1, 1) NOT NULL,
    [ActionUserNotificationOnCancel]  BIT             NULL,
    [ActionUserNotificationOnComment] BIT             NULL,
    [ActualHoursByUser]               BIT             DEFAULT ((0)) NOT NULL,
    [EnableCloseOnHoldExpire]         BIT             DEFAULT ((0)) NOT NULL,
    [AllowBatchClose]                 BIT             NULL,
    [AllowBatchCreate]                BIT             NULL,
    [AllowBatchEditing]               BIT             NULL,
    [AllowChangeType]                 BIT             NULL,
    [AllowDelete]                     BIT             NULL,
    [AllowDraftMode]                  BIT             NULL,
    [AllowEscalationFromList]         BIT             NULL,
    [AllowReassignFromList]           BIT             NULL,
    [AuthorizedToCreate]              NVARCHAR (250)  NULL,
    [AuthorizedToView]                NVARCHAR (250)  NULL,
    [AutoCreateDocumentLibrary]       BIT             NULL,
    [CategoryName]                    NVARCHAR (250)  NULL,
    [CloseChart]                      NVARCHAR (250)  NULL,
    [CustomProperties]                NVARCHAR (MAX)  NULL,
    [DisableNewConfirmation]          BIT             NULL,
    [EnableCache]                     BIT             NULL,
    [EnableEventReceivers]            BIT             NULL,
    [EnableLayout]                    BIT             NULL,
    [EnableModule]                    BIT             NULL,
    [EnableModuleAgent]               BIT             NULL,
    [EnableNewsOnHomePage]            BIT             DEFAULT ((0)) NULL,
    [EnableQuick]                     BIT             NULL,
    [EnableRMMAllocation]             BIT             NULL,
    [EnableWorkflow]                  BIT             NULL,
    [HideWorkFlow]                    BIT             NULL,
    [InitiatorNotificationOnCancel]   BIT             NULL,
    [InitiatorNotificationOnComment]  BIT             NULL,
    [ItemOrder]                       INT             NULL,
    [KeepItemOpen]                    BIT             NULL,
    [LastSequence]                    INT             NULL,
    [LastSequenceDate]                DATETIME        NULL,
    [ModuleAutoApprove]               BIT             NULL,
    [ModuleDescription]               NVARCHAR (MAX)  NULL,
    [ModuleHoldMaxStage]              INT             NULL,
    [ModuleId]                        INT             NULL,
    [ModuleName]                      NVARCHAR (250)  NOT NULL,
    [ModuleRelativePagePath]          NVARCHAR (250)  NULL,
    [ModuleTable]                     NVARCHAR (250)  NULL,
    [ModuleType]                      INT             DEFAULT ((0)) NOT NULL,
    [NavigationUrl]                   NVARCHAR (MAX)  NULL,
    [OpenChart]                       NVARCHAR (250)  NULL,
    [OwnerBindingChoice]              NVARCHAR (MAX)  NULL,
    [PreloadAllModuleTabs]            BIT             NULL,
    [ReloadCache]                     BIT             NULL,
    [RequestorNotificationOnCancel]   BIT             NULL,
    [RequestorNotificationOnComment]  BIT             NULL,
    [ReturnCommentOptional]           BIT             NULL,
    [ShortName]                       NVARCHAR (250)  NULL,
    [ShowBottleNeckChart]             BIT             NULL,
    [ShowComment]                     BIT             NULL,
    [ShowNextSLA]                     BIT             NULL,
    [ShowSummary]                     BIT             NULL,
    [StaticModulePagePath]            NVARCHAR (250)  NULL,
    [StoreEmails]                     BIT             NULL,
    [SyncAppsToRequestType]           BIT             NULL,
    [ThemeColor]                      NVARCHAR (MAX)  NULL,
    [UseInGlobalSearch]               BIT             NULL,
    [WaitingOnMeIncludesGroups]       BIT             NULL,
    [WaitingOnMeExcludesResolved]     BIT             DEFAULT ((0)) NULL,
    [Title]                           VARCHAR (250)   NULL,
    [AutoRefreshListFrequency]        INT      DEFAULT ((0))       NULL,
    [TenantID]                        NVARCHAR (128)  NOT NULL,
    [Created]                         DATETIME        DEFAULT (getdate()) NOT NULL,
    [Modified]                        DATETIME        DEFAULT (getdate()) NOT NULL,
    [CreatedByUser]                   NVARCHAR (128)  DEFAULT ('00000000-0000-0000-0000-000000000000') NOT NULL,
    [ModifiedByUser]                  NVARCHAR (128)  DEFAULT ('00000000-0000-0000-0000-000000000000') NOT NULL,
    [Deleted]                         BIT             DEFAULT ((0)) NULL,
    [Attachments]                     NVARCHAR (2000) DEFAULT ('') NULL,
    [EnableBaseLine]                  BIT             DEFAULT ((0)) NULL,
    [ShowTasksInProjectTasks]         BIT             DEFAULT ((0)) NULL,
    [EnableTicketImport]              BIT             DEFAULT ((0)) NOT NULL,
    [HoldMaxStage]                    INT             DEFAULT ((0)) NOT NULL,
    [KeepTicketCounts]                BIT             DEFAULT ((0)) NOT NULL,
    [NavigationType]				  NVARCHAR (250)  NULL,
	[EnableLinkSimilarTickets]        BIT             DEFAULT ((0)) NULL,
	EnableIcon bit default((0)) null
    CONSTRAINT [PK_Config_Modules] PRIMARY KEY CLUSTERED ([ModuleName] ASC, [TenantID] ASC), 
    [AltTicketIdField] VARCHAR(100) NULL, 
    [EnableAddNewButton] BIT NULL DEFAULT 1
);





GO
CREATE NONCLUSTERED INDEX [IX_Config_Modules_ActualHoursByUser] ON [dbo].[Config_Modules] ([ActualHoursByUser])

GO
CREATE NONCLUSTERED INDEX [IX_Config_Modules_ModuleId] ON [dbo].[Config_Modules] ([ModuleId])

