CREATE TABLE [dbo].[CRMContact] (
    [ID]                     BIGINT         IDENTITY (1, 1) NOT NULL,
    [PctComplete]            INT            NULL,
    [StageActionUserTypes]   NVARCHAR (250) NULL,
    [StageActionUsersUser]   NVARCHAR (250) NULL,
    [AddressedAs]            NVARCHAR (250) NULL,
    [CategoryLookup]         BIGINT         NULL,
    [City]                   NVARCHAR (250) NULL,
    [CloseDate]              DATETIME       NULL,
    [Comment]                NVARCHAR (MAX) NULL,
    [ContactMethodChoice]    NVARCHAR (250) NULL,
    [Country]                NVARCHAR (250) NULL,
    [CRMCompanyLookup]       NVARCHAR (250) NULL,
    [CRMContactType]         NVARCHAR (250) NULL,
    [CurrentStageStartDate]  DATETIME       NULL,
    [DataEditors]            NVARCHAR (250) NULL,
    [Description]            NVARCHAR (MAX) NULL,
    [DesiredCompletionDate]  DATETIME       NULL,
    [DueDate]                DATETIME       NULL,
    [EmailAddress]           NVARCHAR (255) NULL,
    [SecondaryEmail]         NVARCHAR (255) NULL,
    [Fax]                    NVARCHAR (250) NULL,
    [Mobile]                 NVARCHAR (255) NULL,
    [MobilePhone]            NVARCHAR (255) NULL,
    [FirstName]              NVARCHAR (255) NULL,
    [MiddleName]             NVARCHAR (255) NULL,
    [LastName]               NVARCHAR (255) NULL,
    [Initials]               NVARCHAR (255) NULL,
    [FunctionalAreaLookup]   BIGINT         NULL,
    [History]                NVARCHAR (MAX) NULL,
    [ImpactLookup]           BIGINT         NULL,
    [InitiatorUser]          NVARCHAR (MAX) NULL,
    [IsPrivate]              BIT            NULL,
    [LastContacted]          DATETIME       NULL,
    [NameTitle]              NVARCHAR (255) NULL,
    [ModuleStepLookup]       BIGINT         NULL,
    [OnHoldReasonChoice]     NVARCHAR (250) NULL,
    [OnHoldStartDate]        DATETIME       NULL,
    [OnHoldTillDate]         DATETIME       NULL,
    [ORPUser]                NVARCHAR (MAX) NULL,
    [OwnerUser]              NVARCHAR (MAX) NULL,
    [OwnershipTypeChoice]    NVARCHAR (250) NULL,
    [PriorityLookup]         BIGINT         NULL,
    [Prefix]                 NVARCHAR (255) NULL,
    [PRPUser]                NVARCHAR (MAX) NULL,
    [PRPGroupUser]           NVARCHAR (MAX) NULL,
    [RegionsofWorkChoice]    NVARCHAR (250) NULL,
    [RelationshipType]       NVARCHAR (250) NULL,
    [RelationshipTypeLookup] NVARCHAR (250) NULL,
    [RequestTypeLookup]      BIGINT         NULL,
    [ResolutionTypeChoice]   NVARCHAR (250) NULL,
    [ReSubmissionDate]       DATETIME       NULL,
    [ServiceLookup]          BIGINT         NULL,
    [StageStep]              INT            NULL,
    [StartDate]              DATETIME       NULL,
    [State]                  NVARCHAR (250) NULL,
    [StateLookup]            BIGINT         NULL,
    [Status]                 NVARCHAR (250) NULL,
    [StatusChanged]          INT            NULL,
    [StreetAddress1]         NVARCHAR (250) NULL,
    [StreetAddress2]         NVARCHAR (250) NULL,
    [TargetCompletionDate]   DATETIME       NULL,
    [TargetStartDate]        DATETIME       NULL,
    [Telephone]              NVARCHAR (250) NULL,
    [Closed]                 BIT            NULL,
    [Created]                DATETIME       NULL,
    [TicketId]               NVARCHAR (250) NULL,
    [OnHold]                 INT            NULL,
    [Title]                  NVARCHAR (250) NULL,
    [TotalHoldDuration]      INT            NULL,
    [WorkflowSkipStages]     NVARCHAR (250) NULL,
    [Zip]                    NVARCHAR (250) NULL,
    [CreatedByUser]          NVARCHAR (128) NULL,
    [Modified]               DATETIME       NULL,
    [ModifiedByUser]         NVARCHAR (128) NULL,
    [TenantID]               NVARCHAR (128) NULL,
    [Deleted]                BIT            NULL,
    [Attachments]            NVARCHAR (MAX) NULL,
    [CreationDate]           DATETIME       NULL,
    [DataMigrationID]        INT            NULL,
	[ExternalID]			 NVARCHAR (MAX)  NULL,
    [ReopenCount] INT NULL, 
    [ApprovalDate] DATETIME NULL, 
    [ApprovedByUser] VARCHAR(128) NULL, 
    CONSTRAINT [PK_CRMContact] PRIMARY KEY CLUSTERED ([ID] ASC)
);






