CREATE TABLE [dbo].[CRMProject] (
    [ID]                             BIGINT          IDENTITY (1, 1) NOT NULL,
    [CCOs]                           INT             NULL,
    [PCOs]                           INT             NULL,
    [RFIs]                           INT             NULL,
    [PctComplete]                    INT             NULL,
    [AcceptedDate]                   DATETIME        NULL,
    [ActionUserTypes]                NVARCHAR (255)  NULL,
    [ActionUsers]                    NVARCHAR (255)  NULL,
    [ActualCompletionDate]           DATETIME        NULL,
    [ActualLabor]                    NVARCHAR (255)  NULL,
    [ActualLabourHours]              INT             NULL,
    [ActualStartDate]                DATETIME        NULL,
    [AdditionalInfo]                 NVARCHAR (255)  NULL,
    [Address]                        NVARCHAR (MAX)  NULL,
    [AllCCOs]                        NVARCHAR (255)  NULL,
    [APMPctAlloc]                    INT             NULL,
    [ApprovedChangeOrders]           NVARCHAR (255)  NULL,
    [ApproxContractValue]            FLOAT (53)      NULL,
    [AssistantProjectManagerUser]    NVARCHAR (MAX)  NULL,
    [AwardedorLossDate]              DATETIME        NULL,
    [BidAmount]                      NVARCHAR (255)  NULL,
    [BidDueDate]                     DATETIME        NULL,
    [BillingsVariance]               NVARCHAR (255)  NULL,
    [BudgetAmount]                   NVARCHAR (255)  NULL,
    [BudgetChange]                   INT             NULL,
    [BudgetContingency]              NVARCHAR (255)  NULL,
    [BusinessUnitLookup]             BIGINT          NULL,
    [CategoryLookup]                 BIGINT          NULL,
    [ChangeOrderVariance]            NVARCHAR (255)  NULL,
    [City]                           NVARCHAR (255)  NULL,
    [ClientAcceptance]               BIT             NULL,
    [CloseDate]                      DATETIME        NULL,
    [Comment]                        NVARCHAR (MAX)  NULL,
    [ContactLookup]                  NVARCHAR (1000) NULL,
    [ContractAmount]                 NVARCHAR (255)  NULL,
    [ContractedAmount]               NVARCHAR (255)  NULL,
    [CostVariance]                   INT             NULL,
    [Country]                        NVARCHAR (255)  NULL,
    [Created]                        DATETIME        DEFAULT (getdate()) NOT NULL,
    [CRMBusinessUnitChoice]          NVARCHAR (255)  NULL,
    [CRMDuration]                    INT             NULL,
    [CRMProjectStatusChoice]         NVARCHAR (255)  NULL,
    [CurrentBudget]                  NVARCHAR (255)  NULL,
    [CurrentStageStartDate]          DATETIME        NULL,
    [DataEditors]                    NVARCHAR (255)  NULL,
    [DaysToCloseCCO]                 INT             NULL,
    [DaysToResolvePunchList]         INT             NULL,
    [DaysToRespondToRFIs]            INT             NULL,
    [Description]                    NVARCHAR (MAX)  NULL,
    [DesiredCompletionDate]          DATETIME        NULL,
    [DueDate]                        DATETIME        NULL,
    [Duration]                       INT             NULL,
    [EndDateVariance]                INT             NULL,
    [EstimateNo]                     NVARCHAR (255)  NULL,
    [EstimatedConstructionEnd]       DATETIME        NULL,
    [EstimatedConstructionStart]     DATETIME        NULL,
    [EstimatedCost]                  NVARCHAR (255)  NULL,
    [EstimatedCostAtCompletion]      NVARCHAR (255)  NULL,
    [EstimatorUser]                  NVARCHAR (MAX)  NULL,
    [EstimatorPctAlloc]              INT             NULL,
    [ExtClientPaid]                  NVARCHAR (255)  NULL,
    [ExtUnpaidCosts]                 NVARCHAR (255)  NULL,
    [ExternalCCOs]                   NVARCHAR (255)  NULL,
    [ExternalProjectId]              NVARCHAR (255)  NULL,
    [FinalCommitment]                NVARCHAR (255)  NULL,
    [History]                        NVARCHAR (MAX)  NULL,
    [InitiatorUser]                  NVARCHAR (MAX)  NULL,
    [IntClientPaid]                  NVARCHAR (255)  NULL,
    [IntUnpaidCosts]                 NVARCHAR (255)  NULL,
    [InternalCCOs]                   NVARCHAR (255)  NULL,
    [InternalPCOs]                   INT             NULL,
    [IsLead]                         BIT             NULL,
    [IsPrivate]                      BIT             NULL,
    [LaborBudget]                    NVARCHAR (255)  NULL,
    [LaborVariance]                  NVARCHAR (255)  NULL,
    [LabourHourVariance]             INT             NULL,
    [LeadLevelChoice]                NVARCHAR (255)  NULL,
    [ManagerApprovalNeeded]          BIT             NULL,
    [MarketSector]                   NVARCHAR (255)  NULL,
    [Modified]                       DATETIME        DEFAULT (getdate()) NOT NULL,
    [ModuleStepLookup]               BIGINT          NULL,
    [NoChargeChangeOrders]           NVARCHAR (255)  NULL,
    [NonCommittedCosts]              NVARCHAR (255)  NULL,
    [Note]                           NVARCHAR (MAX)  NULL,
    [OnHoldReasonChoice]             NVARCHAR (255)  NULL,
    [OnHoldStartDate]                DATETIME        NULL,
    [OnHoldTillDate]                 DATETIME        NULL,
    [OpenPunchListitems]             INT             NULL,
    [OPMIdLookup]                    NVARCHAR (250)  NULL,
    [OpportunityTypeChoice]          NVARCHAR (255)  NULL,
    [OriginalCommitments]            NVARCHAR (255)  NULL,
    [OrignalEndDate]                 DATETIME        NULL,
    [OrignalStartDate]               DATETIME        NULL,
    [ORPUser]                        NVARCHAR (MAX)  NULL,
    [OverUnders]                     NVARCHAR (255)  NULL,
    [OwnerUser]                      NVARCHAR (MAX)  NULL,
    [PctActualProfit]                INT             NULL,
    [PctGap]                         INT             NULL,
    [PctPlannedProfit]               INT             NULL,
    [PendingOversUnder]              NVARCHAR (255)  NULL,
    [PendingRevisions]               NVARCHAR (255)  NULL,
    [PlannedLabourHours]             INT             NULL,
    [PlannedProfit]                  NVARCHAR (255)  NULL,
    [PreconStartDate]                DATETIME        NULL,
    [ProfitVariance]                 NVARCHAR (255)  NULL,
    [ProjectBillings]                NVARCHAR (255)  NULL,
    [ProjectCollections]             NVARCHAR (255)  NULL,
    [ProjectCost]                    FLOAT (53)      CONSTRAINT [DF_CRMProject_ProjectCost] DEFAULT ((0)) NULL,
    [ProjectExecutiveUser]           NVARCHAR (MAX)  NULL,
    [ProjectExecutivePctAlloc]       INT             NULL,
    [ProjectId]                      NVARCHAR (255)  NULL,
    [ProjectManagerUser]             NVARCHAR (MAX)  NULL,
    [ProjectManagerPctAlloc]         INT             NULL,
    [ProjectName]                    NVARCHAR (255)  NULL,
    [ProjectTemplate]                NVARCHAR (255)  NULL,
    [ProjectedBudget]                NVARCHAR (255)  NULL,
    [PRPUser]                        NVARCHAR (MAX)  NULL,
    [PRPGroupUser]                   NVARCHAR (MAX)  NULL,
    [PunchListItems]                 INT             NULL,
    [Reason]                         NVARCHAR (255)  NULL,
    [RequestTypeLookup]              BIGINT          NULL,
    [ResolutionTypeChoice]           NVARCHAR (255)  NULL,
    [ReSubmissionDate]               DATETIME        NULL,
    [RetailSqft]                     NVARCHAR (255)  NULL,
    [RetailSqftNum]                  INT             NULL,
    [RevisedBudget]                  NVARCHAR (255)  NULL,
    [RevisedContract]                NVARCHAR (255)  NULL,
    [RevisedEndDate]                 DATETIME        NULL,
    [RevisedStartDate]               DATETIME        NULL,
    [ScheduleVariance]               INT             NULL,
    [StageStep]                      INT             NULL,
    [StartDate]                      DATETIME        NULL,
    [StartDateVariance]              INT             NULL,
    [StateLookup]                    BIGINT          NULL,
    [Status]                         NVARCHAR (255)  NULL,
    [StatusChanged]                  INT             NULL,
    [StreetAddress1]                 NVARCHAR (255)  NULL,
    [SubstatusLookup]                BIGINT          NULL,
    [SuperintendentUser]             NVARCHAR (MAX)  NULL,
    [SuperintendentPctAlloc]         INT             NULL,
    [StageActionUserTypes]           NVARCHAR (250)  NULL,
    [StageActionUsersUser]           NVARCHAR (MAX)  NULL,
    [TargetCompletionDate]           DATETIME        NULL,
    [TargetStartDate]                DATETIME        NULL,
    [Closed]                         BIT             NULL,
    [CreationDate]                   DATETIME        NULL,
    [OnHold]                         INT             NULL,
    [RequestTypeSubCategory]         NVARCHAR (250)  NULL,
    [Title]                          NVARCHAR (255)  NULL,
    [TicketId]                       NVARCHAR (250)  NULL,
    [TotalHoldDuration]              INT             NULL,
    [UsableSqFt]                     NVARCHAR (255)  NULL,
    [UsableSqFtNum]                  INT             NULL,
    [WorkflowSkipStages]             NVARCHAR (255)  NULL,
    [WorkflowType]                   BIGINT          NULL,
    [Zip]                            NVARCHAR (255)  NULL,
    [TenantID]                       NVARCHAR (128)  NULL,
    [CreatedByUser]                  NVARCHAR (MAX)  DEFAULT ('00000000-0000-0000-0000-000000000000') NOT NULL,
    [ModifiedByUser]                 NVARCHAR (MAX)  DEFAULT ('00000000-0000-0000-0000-000000000000') NOT NULL,
    [Attachments]                    NVARCHAR (2000) NULL,
    [Deleted]                        BIT             DEFAULT ((0)) NULL,
    [LEMIdLookup]                    NVARCHAR (250)  NULL,
    [CRMProjectComplexityChoice]     NVARCHAR(10)             NULL,
    [DataMigrationID]                INT             NULL,
    [SectorChoice]				     NVARCHAR (250)  NULL,
    [APMUser]                        NVARCHAR (MAX)  NULL,
    [PreConstruction]                NVARCHAR (MAX)  NULL,
    [CRMUser]                        NVARCHAR (MAX)  NULL,
    [CRMAdminUser]                   NVARCHAR (MAX)  NULL,
    [PreConAdminUser]                NVARCHAR (MAX)  NULL,
    [ProjectEngineerUser]            NVARCHAR (MAX)  NULL,
    [FieldOperationsManagerUser]     NVARCHAR (MAX)  NULL,
    [SafetyManagerUser]              NVARCHAR (MAX)  NULL,
    [QualityControlCoordinatorUser]  NVARCHAR (MAX)  NULL,
    [FieldEngineerUser]              NVARCHAR (MAX)  NULL,
    [CarpenterUser]                  NVARCHAR (MAX)  NULL,
    [CarpenterApprenticeUser]        NVARCHAR (MAX)  NULL,
    [CarpenterForemanUser]           NVARCHAR (MAX)  NULL,
    [AssistantSuperintendentUser]    NVARCHAR (MAX)  NULL,
    [LaborerSuperintendentUser]      NVARCHAR (MAX)  NULL,
    [LaborerForemanUser]             NVARCHAR (MAX)  NULL,
    [LaborerUser]                    NVARCHAR (MAX)  NULL,
    [ArchitectUser]                  NVARCHAR (MAX)  NULL,
    [BusinessDevelopmentManagerUser] NVARCHAR (MAX)  NULL,
    [ManagerServiceGroupUser]        NVARCHAR (MAX)  NULL,
    [MEPCoordinatorUser]             NVARCHAR (MAX)  NULL,
    [ProgramManagerUser]             NVARCHAR (MAX)  NULL,
    [ProjectManagerArchitectureUser] NVARCHAR (MAX)  NULL,
    [ProjectManagerServiceGroupUser] NVARCHAR (MAX)  NULL,
    [SeniorManagerAccountingUser]    NVARCHAR (MAX)  NULL,
    [ServiceCoordinatorUser]         NVARCHAR (MAX)  NULL,
    [SustainbilityAssociateUser]     NVARCHAR (MAX)  NULL,
    [SustainbilityCoordinatorUser]   NVARCHAR (MAX)  NULL,
    [OwnerContractTypeChoice]        NVARCHAR (255)  NULL,
    [StudioChoice]                   NVARCHAR (255)  NULL,
    [SignedNDA]                      BIT             DEFAULT ((0)) NULL,
	[CRMCompanyLookup]				 NVARCHAR (250)  NULL,
	[PreconEndDate]					 DATETIME        NULL,
	[ExternalID]					 NVARCHAR (MAX)  NULL,
	[ProjectRank]					 NVARCHAR (255)  NULL,
	[PreconLeadUser]			  	 NVARCHAR (MAX)  NULL,
	[IconBlob]							varbinary(max) NULL,
    [StudioLookup]                 BIGINT null,
    [ERPJobID]    nvarchar(500) NULL,
	[ApprenticeArchitectUser]       NVARCHAR (MAX)  NULL,
	[ProjectAuditorUser]            NVARCHAR (MAX)  NULL,
    [Change_Orders] nvarchar(255) NULL,
	[SubContract]  nvarchar(255) NULL,
	[Approved_SCO]  nvarchar(255) NULL,
	[Resource_Costs]  nvarchar(255) NULL,
	[Resource_Util]  nvarchar(255) NULL,
	[OCOs]  int NULL,
	[SCOs]  int NULL,
	[Submittals]  int NULL,
	[Drawings]  int NULL,
	[Action_Items]  int NULL,
	[GrossP]  nvarchar(255) NULL,
	[GrossD]  nvarchar(255) NULL,
	[Real_Income]  nvarchar(255) NULL,
	[ProjectRisk]  int NULL,
	[ProjectComplexityScore]  float NULL,
	[ProjectValue]  int NULL,
	[ProjectSimilarity]  int NULL,
	[ProjectReview]   int NULL,
	[DivisionChoice]    varchar(max) NULL,
    [EnableStdWorkItems] BIT NULL , 
    [FeePct] decimal(6,2) NULL,
    [CloseoutDate] DATETIME NULL,
    [ReopenCount] INT NULL, 
    [ERPJobIDNC]    nvarchar(500) NULL,
    [ApprovalDate] DATETIME NULL, 
    [ApprovedByUser] VARCHAR(MAX) NULL, 
    [HasPreconstructionContract] BIT DEFAULT 0,
    [ProjectLeadUser] NVARCHAR(MAX) NULL,
    [LeadEstimatorUser] NVARCHAR(MAX) NULL,
    [LeadSuperintendentUser] NVARCHAR(MAX) NULL,
    [ShortName] VARCHAR(20) NULL, 
    CONSTRAINT [PK_CRMProject] PRIMARY KEY CLUSTERED ([ID] ASC)
);








