CREATE TABLE [dbo].[Customers] (
    [ID]                       BIGINT          IDENTITY (1, 1) NOT NULL,
    [AccountAddress]           NVARCHAR (MAX)  NULL,
    [AccountManager]           NVARCHAR (MAX)  NULL,
    [AccountName]              NVARCHAR (250)  NULL,
    [AcquiredBy]               NVARCHAR (MAX)  NULL,
    [ActualCompletionDate]     DATETIME        NULL,
    [ActualStartDate]          DATETIME        NULL,
    [BusinessManagerUser]      NVARCHAR (MAX)  NULL,
    [CampaignInfo]             NVARCHAR (MAX)  NULL,
    [CampaignStrategy]         NVARCHAR (MAX)  NULL,
    [CampaignUsed]             NVARCHAR (MAX)  NULL,
    [ChanceOfSuccessChoice]    NVARCHAR (MAX)  NULL,
    [Closed]                   BIT             NULL,
    [CloseDate]                DATETIME        NULL,
    [Comment]                  NVARCHAR (MAX)  NULL,
    [Company]                  NVARCHAR (250)  NULL,
    [CreationDate]             DATETIME        NULL,
    [CurrentStageStartDate]    DATETIME        NULL,
    [CustomerAccountSize]      INT             NULL,
    [CustomerAccountType]      NVARCHAR (MAX)  NULL,
    [CustomerAccountVertical]  NVARCHAR (MAX)  NULL,
    [CustomerSource]           NVARCHAR (MAX)  NULL,
    [Description]              NVARCHAR (MAX)  NULL,
    [DesiredCompletionDate]    DATETIME        NULL,
    [Duration]                 INT             NULL,
    [EmailAddress]             NVARCHAR (250)  NULL,
    [FacebookPage]             NVARCHAR (250)  NULL,
    [FirstName]                NVARCHAR (250)  NULL,
    [History]                  NVARCHAR (MAX)  NULL,
    [IdentifiedBy]             NVARCHAR (MAX)  NULL,
    [InitialCost]              NVARCHAR (250)  NULL,
    [InitiatorUser]            NVARCHAR (MAX)  NULL,
    [IsPrivate]                BIT             NULL,
    [JobTitle]                 NVARCHAR (250)  NULL,
    [LastName]                 NVARCHAR (250)  NULL,
    [LeadStatus]               NVARCHAR (MAX)  NULL,
    [LinkedInPage]             NVARCHAR (250)  NULL,
    [ModuleStepLookup]         NVARCHAR (250)  NULL,
    [NoOfEmployee]             INT             NULL,
    [OnHold]                   INT             NULL,
    [OnHoldReasonChoice]       NVARCHAR (MAX)  NULL,
    [OnHoldStartDate]          DATETIME        NULL,
    [OnHoldTillDate]           DATETIME        NULL,
    [OwnerUser]                NVARCHAR (250)  NULL,
    [PctComplete]              INT             NULL,
    [PriorityLookup]           BIGINT          NOT NULL,
    [Quality]                  NVARCHAR (MAX)  NULL,
    [RequestorUser]            NVARCHAR (250)  NULL,
    [RequestSourceChoice]      NVARCHAR (MAX)  NULL,
    [RequestTypeCategory]      NVARCHAR (250)  NULL,
    [RequestTypeLookup]        BIGINT          NOT NULL,
    [RequestTypeWorkflow]      NVARCHAR (250)  NULL,
    [ResolutionComments]       NVARCHAR (MAX)  NULL,
    [ReSubmissionDate]         DATETIME        NULL,
    [Revenues]                 NVARCHAR (250)  NULL,
    [SICCode]                  NVARCHAR (250)  NULL,
    [SourceDetails]            NVARCHAR (MAX)  NULL,
    [StageActionUsersUser]     NVARCHAR (250)  NULL,
    [StageActionUserTypes]     NVARCHAR (250)  NULL,
    [StageStep]                INT             NULL,
    [Status]                   NVARCHAR (250)  NULL,
    [StatusChanged]            INT             NULL,
    [TargetCompletionDate]     DATETIME        NULL,
    [TargetStartDate]          DATETIME        NULL,
    [TaskActualCompletionDate] DATETIME        NULL,
    [TaskActualStartDate]      DATETIME        NULL,
    [TicketId]                 NVARCHAR (250)  NULL,
    [Title]                    NVARCHAR (250)  NULL,
    [TotalHoldDuration]        INT             NULL,
    [TwitterPage]              NVARCHAR (250)  NULL,
    [URL]                      NVARCHAR (250)  NULL,
    [VendorPhone]              NVARCHAR (250)  NULL,
    [WorkAddress]              NVARCHAR (MAX)  NULL,
    [TenantID]                 NVARCHAR (128)  NULL,
    [DataEditors]              NVARCHAR (250)  CONSTRAINT [DF__Customers__DataE__6C8E1007] DEFAULT ('') NULL,
    [Created]                  DATETIME        CONSTRAINT [DF__Customers__Creat__6D823440] DEFAULT (getdate()) NOT NULL,
    [Modified]                 DATETIME        CONSTRAINT [DF__Customers__Modif__6E765879] DEFAULT (getdate()) NOT NULL,
    [CreatedByUser]            NVARCHAR (128)  CONSTRAINT [DF__Customers__Creat__6F6A7CB2] DEFAULT ('00000000-0000-0000-0000-000000000000') NOT NULL,
    [ModifiedByUser]           NVARCHAR (128)  CONSTRAINT [DF__Customers__Modif__705EA0EB] DEFAULT ('00000000-0000-0000-0000-000000000000') NOT NULL,
    [Deleted]                  BIT             CONSTRAINT [DF__Customers__Delet__7152C524] DEFAULT ((0)) NULL,
    [Attachments]              NVARCHAR (2000) CONSTRAINT [DF__Customers__Attac__7246E95D] DEFAULT ('') NULL,
    CONSTRAINT [PK__Customer__3214EC27F9FA394A] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK__Customers__Prior__096A45D7] FOREIGN KEY ([PriorityLookup]) REFERENCES [dbo].[Config_Module_Priority] ([ID]),
    CONSTRAINT [FK__Customers__Reque__0A5E6A10] FOREIGN KEY ([RequestTypeLookup]) REFERENCES [dbo].[Config_Module_RequestType] ([ID])
);












GO

GO
