CREATE TABLE [dbo].[DMPortalInfo] (
    [ID]                                BIGINT          IDENTITY (1, 1) NOT NULL,
    [AllowAllTypes]                     BIT             NULL,
    [AlternateOwner]                    NVARCHAR (MAX)  NULL,
    [AlwaysNotifyOwnerOnReviewComplete] BIT             NULL,
    [AlwaysNotifyOwnerOnReviewStart]    BIT             NULL,
    [AlwaysReviewRequired]              BIT             NULL,
    [Authors]                           NVARCHAR (250)  NULL,
    [CCUser]                            NVARCHAR (250)  NULL,
    [DCLastSequence]                    NVARCHAR (250)  NULL,
    [Green]                             NVARCHAR (250)  NULL,
    [IsDocumentID]                      BIT             NULL,
    [IsFolderProperties]                BIT             NULL,
    [IsPortalProjectType]               BIT             NULL,
    [IsSizeUnlimited]                   BIT             NULL,
    [KeepDocsAlive]                     NVARCHAR (250)  NULL,
    [KeepNYear]                         NVARCHAR (250)  NULL,
    [ModuleNameLookup]                  NVARCHAR (250)  NULL,
    [NotifyAuthor]                      BIT             NULL,
    [NotifyOnReviewComplete]            NVARCHAR (250)  NULL,
    [NotifyOwnerBeforeDeletion]         BIT             NULL,
    [NotifyOwnerOnDocUpload]            BIT             NULL,
    [NotifyReader]                      BIT             NULL,
    [NotifyUserOnReviewStart]           NVARCHAR (250)  NULL,
    [NumFiles]                          NVARCHAR (250)  NULL,
    [NumOfReviewCycle]                  INT             NULL,
    [NumVersions]                       NVARCHAR (250)  NULL,
    [PortalDescription]                 NVARCHAR (MAX)  NULL,
    [PortalId]                          NVARCHAR (250)  NULL,
    [PortalName]                        NVARCHAR (250)  NULL,
    [PortalOwner]                       NVARCHAR (250)  NULL,
    [PrefixAcronym]                     BIT             NULL,
    [Readers]                           NVARCHAR (250)  NULL,
    [Red]                               NVARCHAR (250)  NULL,
    [ReviewCycle1]                      NVARCHAR (250)  NULL,
    [ReviewCycle10]                     NVARCHAR (250)  NULL,
    [ReviewCycle2]                      NVARCHAR (250)  NULL,
    [ReviewCycle3]                      NVARCHAR (250)  NULL,
    [ReviewCycle4]                      NVARCHAR (250)  NULL,
    [ReviewCycle5]                      NVARCHAR (250)  NULL,
    [ReviewCycle6]                      NVARCHAR (250)  NULL,
    [ReviewCycle7]                      NVARCHAR (250)  NULL,
    [ReviewCycle8]                      NVARCHAR (250)  NULL,
    [ReviewCycle9]                      NVARCHAR (250)  NULL,
    [ReviewRequired]                    BIT             NULL,
    [SizeOfFolder]                      NVARCHAR (250)  NULL,
    [UseDefaultCategory]                BIT             NULL,
    [Yellow]                            NVARCHAR (250)  NULL,
    [Title]                             VARCHAR (250)   NULL,
    [TenantID]                          NVARCHAR (128)  NULL,
    [Created]                           DATETIME        DEFAULT (getdate()) NOT NULL,
    [Modified]                          DATETIME        DEFAULT (getdate()) NOT NULL,
    [CreatedByUser]                     NVARCHAR (128)  DEFAULT ('00000000-0000-0000-0000-000000000000') NOT NULL,
    [ModifiedByUser]                    NVARCHAR (128)  DEFAULT ('00000000-0000-0000-0000-000000000000') NOT NULL,
    [Deleted]                           BIT             DEFAULT ((0)) NULL,
    [Attachments]                       NVARCHAR (2000) DEFAULT ('') NULL
);







