
CREATE TABLE [dbo].[DMSFileAuditLog]
(
	[FileAuditLogId] [INT] IDENTITY(1,1) NOT NULL,
	[FileId] [INT] NOT NULL,
	[UserId] NVARCHAR(128) NOT NULL,
	[CheckOutDate] [DATETIME] NOT NULL,
	[CheckInDate] [DATETIME] NOT NULL,
 CONSTRAINT [PK_FileAuditLog] PRIMARY KEY CLUSTERED 
(
	[FileAuditLogId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO