CREATE TABLE [dbo].[Lead] (
    [ID]                         BIGINT          IDENTITY (1, 1) NOT NULL,
    [PctComplete]                INT             NULL,
    [StageActionUserTypes]       NVARCHAR (250)  NULL,
    [StageActionUsersUser]       NVARCHAR (250)  NULL,
    [AdditionalDetail]           NVARCHAR (250)  NULL,
    [AdditionalInfo]             NVARCHAR (250)  NULL,
    [Address]                    NVARCHAR (MAX)  NULL,
    [CategoryLookup]             BIGINT          NULL,
    [ChanceOfSuccessChoice]      NVARCHAR (250)  NULL,
    [City]                       NVARCHAR (250)  NULL,
    [CloseDate]                  DATETIME        NULL,
    [Comment]                    NVARCHAR (MAX)  NULL,
    [ContactLookup]              NVARCHAR (1000) NULL,
    [Country]                    NVARCHAR (250)  NULL,
    [CurrentStageStartDate]      DATETIME        NULL,
    [DataEditors]                NVARCHAR (250)  NULL,
    [DepartmentLookup]           BIGINT          NULL,
    [Description]                NVARCHAR (MAX)  NULL,
    [DesiredCompletionDate]      DATETIME        NULL,
    [DocumentLibraryName]        NVARCHAR (250)  NULL,
    [DueDate]                    DATETIME        NULL,
    [FunctionalAreaLookup]       BIGINT          NULL,
    [History]                    NVARCHAR (MAX)  NULL,
    [InitiatorUser]              NVARCHAR (MAX)  NULL,
    [IsPrivate]                  BIT             NULL,
    [ManagerApprovalNeeded]      BIT             NULL,
    [ModuleStepLookup]           BIGINT          NULL,
    [OnHoldReasonChoice]         NVARCHAR (250)  NULL,
    [OnHoldStartDate]            DATETIME        NULL,
    [OnHoldTillDate]             DATETIME        NULL,
    [ORPUser]                    NVARCHAR (MAX)  NULL,
    [OwnerUser]                  NVARCHAR (MAX)  NULL,
    [OwnershipTypeChoice]        NVARCHAR (250)  NULL,
    [ProcoreId]                  NVARCHAR (250)  NULL,
    [PRPUser]                    NVARCHAR (MAX)  NULL,
    [PRPGroupUser]               NVARCHAR (MAX)  NULL,
    [RelationshipType]           NVARCHAR (250)  NULL,
    [RelationshipTypeLookup]     NVARCHAR (250)  NULL,
    [RequestTypeLookup]          BIGINT          NULL,
    [ResolutionTypeChoice]       NVARCHAR (250)  NULL,
    [ReSubmissionDate]           DATETIME        NULL,
    [ServiceLookup]              BIGINT          NULL,
    [StageStep]                  INT             NULL,
    [StartDate]                  DATETIME        NULL,
    [State]                      NVARCHAR (250)  NULL,
    [StateLookup]                BIGINT          NULL,
    [Status]                     NVARCHAR (250)  NULL,
    [StatusChanged]              INT             NULL,
    [StreetAddress1]             NVARCHAR (250)  NULL,
    [TargetCompletionDate]       DATETIME        NULL,
    [TargetStartDate]            DATETIME        NULL,
    [Closed]                     BIT             NULL,
    [Created]                    DATETIME        NULL,
    [TicketId]                   NVARCHAR (250)  NULL,
    [OnHold]                     INT             NULL,
    [Title]                      NVARCHAR (250)  NULL,
    [TotalHoldDuration]          INT             NULL,
    [CreationDate]               DATETIME        NULL,
    [WorkflowSkipStages]         NVARCHAR (250)  NULL,
    [Zip]                        NVARCHAR (250)  NULL,
    [CreatedByUser]              NVARCHAR (128)  NULL,
    [Modified]                   DATETIME        NULL,
    [ModifiedByUser]             NVARCHAR (128)  NULL,
    [TenantID]                   NVARCHAR (128)  NULL,
    [Deleted]                    BIT             NULL,
    [Attachments]                NVARCHAR (MAX)  NULL,
    [AnalysisDetail]             NVARCHAR (MAX)  NULL,
    [ApproxContractValue]        FLOAT (53)      NULL,
    [BuildingOwner]              BIGINT          NULL,
    [BuildingOwnerCompany]       BIGINT          NULL,
    [BusinessUnitLookup]         BIGINT          NULL,
    [SuccessChance]              NVARCHAR (250)  NULL,
    [ConstructionManagerContact] BIGINT          NULL,
    [ContractValue]              NVARCHAR (250)  NULL,
    [CRMBusinessUnitChoice]      NVARCHAR (250)  NULL,
    [EstimatedConstructionEnd]   DATETIME        NULL,
    [EstimatedConstructionStart] DATETIME        NULL,
    [IsLead]                     BIT             NULL,
    [LeadSourceCompanyLabel]     NVARCHAR (250)  NULL,
    [LeadStatus]                 NVARCHAR (250)  NULL,
    [LeadLevelChoice]            NVARCHAR (250)  NULL,
    [MarketSector]               NVARCHAR (250)  NULL,
    [OpportunityTypeChoice]      NVARCHAR (250)  NULL,
    [RequestTypeCategory]        NVARCHAR (250)  NULL,
    [RequestTypeSubCategory]     NVARCHAR (250)  NULL,
    [PreconStartDate]            DATETIME        NULL,
    [ProjectName]                NVARCHAR (250)  NULL,
    [ProjectedSize]              NVARCHAR (250)  NULL,
    [ReasonType]                 NVARCHAR (250)  NULL,
    [RetailSqft]                 NVARCHAR (250)  NULL,
    [RetailSqftNum]              INT             NULL,
    [UsableSqFt]                 NVARCHAR (250)  NULL,
    [UsableSqFtNum]              INT             NULL,
    [WorkflowType]               BIGINT          NULL,
    [RankingCriteriaTotal]       NVARCHAR (5)    DEFAULT ((0)) NULL,
    [DataMigrationID]            INT             NULL,
    [SectorChoice]			     NVARCHAR (250)  NULL,
    [ProjectId]                  NVARCHAR (255)  NULL,
    [CRMUrgencyChoice]           NVARCHAR (255)  NULL,
    [LeadSourceLookup]           NVARCHAR (250)  NULL,
    [SignedNDA]                  BIT             DEFAULT ((0)) NULL,
	[CRMCompanyLookup]			 NVARCHAR (250)  NULL,
	[ExternalID]				 NVARCHAR (MAX)  NULL,
    [ReopenCount] INT NULL,
    [ApprovalDate] DATETIME NULL, 
    [ApprovedByUser] VARCHAR(128) NULL,
    [DivisionLookup]  BIGINT  NULL,
    CONSTRAINT [PK_Lead] PRIMARY KEY CLUSTERED ([ID] ASC)
);


