CREATE TABLE [dbo].[NPR] (
    [ID]                                   BIGINT          IDENTITY (1, 1) NOT NULL,
    [ActualCompletionDate]                 DATETIME        NULL,
    [ActualStartDate]                      DATETIME        NULL,
    [AdoptionRiskChoice]                   NVARCHAR (MAX)  NULL,
    [AnalyticsArchitecture]                INT             NULL,
    [AnalyticsCost]                        INT             NULL,
    [AnalyticsRisk]                        INT             NULL,
    [AnalyticsROI]                         INT             NULL,
    [AnalyticsSchedule]                    INT             NULL,
    [ApprovedRFE]                          NVARCHAR (250)  NULL,
    [ApprovedRFEAmount]                    NVARCHAR (250)  NULL,
    [ApprovedRFEType]                      NVARCHAR (MAX)  NULL,
    [APPTitleLookup]                       BIGINT          NULL,
    [ArchitectureScore]                    INT             NULL,
    [ArchitectureScoreNotes]               NVARCHAR (MAX)  NULL,
    [AssignedAnalyst]                      NVARCHAR (MAX)  NULL,
    [AutoAdjustAllocations]                BIT             NULL,
    [BeneficiariesLookup]                  NVARCHAR (250)  NULL,
    [BreakEvenIn]                          INT             NULL,
    [BusinessManagerUser]                  NVARCHAR (MAX)  NULL,
    [CannotStartBefore]                    DATETIME        NULL,
    [CannotStartBeforeNotes]               NVARCHAR (MAX)  NULL,
    [CapitalExpenditure]                   BIT             NULL,
    [CapitalExpenditureNotes]              NVARCHAR (250)  NULL,
    [CapitalExpense]                       NVARCHAR (250)  NULL,
    [ClassificationChoice]                 NVARCHAR (MAX)  NULL,
    [ClassificationImpact]                 NVARCHAR (MAX)  NULL,
    [ClassificationNotes]                  NVARCHAR (MAX)  NULL,
    [ClassificationScopeChoice]            NVARCHAR (MAX)  NULL,
    [ClassificationSizeChoice]                   NVARCHAR (MAX)  NULL,
    [ClassificationTypeChoice]             NVARCHAR (MAX)  NULL,
    [Closed]                               BIT             NULL,
    [CloseDate]                            DATETIME        NULL,
    [Comment]                              NVARCHAR (MAX)  NULL,
    [CompanyMultiLookup]                   BIGINT          NULL,
    [Complexity]                           NVARCHAR (MAX)  NULL,
    [ComplexityNotes]                      NVARCHAR (MAX)  NULL,
    [ConstraintNotes]                      NVARCHAR (MAX)  NULL,
    [CreationDate]                         DATETIME        NULL,
    [CurrentStageStartDate]                DATETIME        NULL,
    [CustomUGChoice01]                     NVARCHAR (MAX)  NULL,
    [CustomUGChoice02]                     NVARCHAR (MAX)  NULL,
    [CustomUGChoice03]                     NVARCHAR (MAX)  NULL,
    [CustomUGChoice04]                     NVARCHAR (MAX)  NULL,
    [CustomUGDate01]                       DATETIME        NULL,
    [CustomUGDate02]                       DATETIME        NULL,
    [CustomUGDate03]                       DATETIME        NULL,
    [CustomUGDate04]                       DATETIME        NULL,
    [CustomUGText01]                       NVARCHAR (250)  NULL,
    [CustomUGText02]                       NVARCHAR (250)  NULL,
    [CustomUGText03]                       NVARCHAR (250)  NULL,
    [CustomUGText04]                       NVARCHAR (250)  NULL,
    [CustomUGText05]                       NVARCHAR (250)  NULL,
    [CustomUGText06]                       NVARCHAR (250)  NULL,
    [CustomUGText07]                       NVARCHAR (250)  NULL,
    [CustomUGText08]                       NVARCHAR (250)  NULL,
    [CustomUGUser01]                       NVARCHAR (MAX)  NULL,
    [CustomUGUser02]                       NVARCHAR (MAX)  NULL,
    [CustomUGUser03]                       NVARCHAR (MAX)  NULL,
    [CustomUGUser04]                       NVARCHAR (MAX)  NULL,
    [CustomUGUserMulti01]                  NVARCHAR (250)  NULL,
    [CustomUGUserMulti02]                  NVARCHAR (250)  NULL,
    [CustomUGUserMulti03]                  NVARCHAR (250)  NULL,
    [CustomUGUserMulti04]                  NVARCHAR (250)  NULL,
    [Description]                          NVARCHAR (MAX)  NULL,
    [DesiredCompletionDate]                DATETIME        NULL,
    [DesiredCompletionDateNotes]           NVARCHAR (MAX)  NULL,
    [DivisionMultiLookup]                  BIGINT          NULL,
    [DocumentLibraryName]                  NVARCHAR (250)  NULL,
    [Duration]                             INT             NULL,
    [EliminatesHeadcount]                  INT             NULL,
    [EstimatedHours]                       INT             NULL,
    [FunctionalAreaLookup]                 BIGINT          NULL,
    [History]                              NVARCHAR (MAX)  NULL,
    [ImpactBusinessGrowthChoice]           NVARCHAR (MAX)  NULL,
    [ImpactDecisionMakingChoice]           NVARCHAR (MAX)  NULL,
    [ImpactIncreasesProductivityChoice]    NVARCHAR (MAX)  NULL,
    [ImpactLookup]                         BIGINT          NULL,
    [ImpactReducesExpensesChoice]          NVARCHAR (MAX)  NULL,
    [ImpactReducesRiskChoice]              NVARCHAR (MAX)  NULL,
    [ImpactRevenueIncreaseChoice]          NVARCHAR (MAX)  NULL,
    [ImprovesOperationalEfficiency]        NVARCHAR (MAX)  NULL,
    [ImprovesRevenues]                     NVARCHAR (MAX)  NULL,
    [InitiatorUser]                        NVARCHAR (MAX)  NULL,
    [InternalCapabilityChoice]             NVARCHAR (MAX)  NULL,
    [IsITGApprovalRequired]                BIT             NULL,
    [IsPrivate]                            BIT             NULL,
    [IsProjectBudgeted]                    BIT             NULL,
    [IsSteeringApprovalRequired]           BIT             NULL,
    [ITGReviewApproval]                    NVARCHAR (MAX)  NULL,
    [ITManager]                            NVARCHAR (MAX)  NULL,
    [ITSteeringCommitteeApproval]          NVARCHAR (MAX)  NULL,
    [LocationMultLookup]                   NVARCHAR (MAX)  NULL,
    [ManagerApprovalNeeded]                BIT             NULL,
    [MetricsNotes]                         NVARCHAR (MAX)  NULL,
    [ModuleNameLookup]                     NVARCHAR (250)  NULL,
    [ModuleStepLookup]                     NVARCHAR (250)  NULL,
    [NextSLATime]                          DATETIME        NULL,
    [NextSLAType]                          NVARCHAR (250)  NULL,
    [NoAlternative]                        NVARCHAR (250)  NULL,
    [NoAlternativeOtherDescribe]           NVARCHAR (MAX)  NULL,
    [NoOfConsultants]                      INT             NULL,
    [NoOfConsultantsNotes]                 NVARCHAR (MAX)  NULL,
    [NoOfFTEs]                             INT             NULL,
    [NoOfFTEsNotes]                        NVARCHAR (MAX)  NULL,
    [NoOfReports]                          INT             NULL,
    [NoOfReportsNotes]                     NVARCHAR (MAX)  NULL,
    [NoOfScreens]                          INT             NULL,
    [NoOfScreensNotes]                     NVARCHAR (MAX)  NULL,
    [OnHold]                               INT             NULL,
    [OnHoldReasonChoice]                   NVARCHAR (MAX)  NULL,
    [OnHoldStartDate]                      DATETIME        NULL,
    [OnHoldTillDate]                       DATETIME        NULL,
    [OrganizationalImpactChoice]           NVARCHAR (MAX)  NULL,
    [OtherDescribe]                        NVARCHAR (MAX)  NULL,
    [OwnerUser]                            NVARCHAR (250)  NULL,
    [PMMIdLookup]                          BIGINT          NULL,
    [PriorityLookup]                       BIGINT          NULL,
    [ProblemBeingSolved]                   NVARCHAR (MAX)  NULL,
    [ProjectAssumptions]                   NVARCHAR (MAX)  NULL,
    [ProjectAssumptionsDescription]        NVARCHAR (MAX)  NULL,
    [ProjectBenefits]                      NVARCHAR (MAX)  NULL,
    [ProjectBenefitsDescription]           NVARCHAR (MAX)  NULL,
    [ProjectComplexityChoice]              NVARCHAR(MAX)             NULL,
    [ProjectCost]                          INT             NULL,
    [ProjectDirector]                      NVARCHAR (MAX)  NULL,
    [ProjectEstDurationMaxDays]            INT             NULL,
    [ProjectEstDurationMinDays]            INT             NULL,
    [ProjectEstSizeMaxHrs]                 INT             NULL,
    [ProjectEstSizeMinHrs]                 INT             NULL,
    [ProjectInitiativeLookup]              BIGINT          NULL,
    [ProjectManagerUser]                   NVARCHAR (250)  NULL,
    [ProjectRank]                          NVARCHAR (250)  NULL,
    [ProjectRank2]                         NVARCHAR (250)  NULL,
    [ProjectRank3]                         NVARCHAR (250)  NULL,
    [ProjectRisk]                          NVARCHAR (MAX)  NULL,
    [ProjectRiskNotes]                     NVARCHAR (MAX)  NULL,
    [ProjectScope]                         NVARCHAR (MAX)  NULL,
    [ProjectScopeDescription]              NVARCHAR (MAX)  NULL,
    [ProjectScore]                         NVARCHAR (250)  NULL,
    [ProjectScoreNotes]                    NVARCHAR (MAX)  NULL,
    [PRPGroupUser]                         NVARCHAR (MAX)  NULL,
    [RapidRequest]                         NVARCHAR (MAX)  NULL,
    [ReducesCost]                          NVARCHAR (MAX)  NULL,
    [RegulatoryCompliance]                 NVARCHAR (MAX)  NULL,
    [RequestorUser]                        NVARCHAR (250)  NULL,
    [RequestTypeCategory]                  NVARCHAR (250)  NULL,
    [RequestTypeLookup]                    BIGINT          NULL,
    [RequestTypeSubCategory]               NVARCHAR (250)  NULL,
    [RequestTypeWorkflow]                  NVARCHAR (250)  NULL,
    [RiskScore]                            INT             NULL,
    [RiskScoreNotes]                       NVARCHAR (MAX)  NULL,
    [ROI]                                  NVARCHAR (250)  NULL,
    [ScheduleComplexity]                   NVARCHAR (MAX)  NULL,
    [SecurityManagerUser]                  NVARCHAR (250)  NULL,
    [ServiceLookUp]                        BIGINT          NULL,
    [SeverityLookup]                       BIGINT          NULL,
    [SponsorsUser]                         NVARCHAR (250)  NULL,
    [StageActionUsersUser]                 NVARCHAR (250)  NULL,
    [StageActionUserTypes]                 NVARCHAR (250)  NULL,
    [StageStep]                            INT             NULL,
    [StakeHoldersUser]                     NVARCHAR (250)  NULL,
    [Status]                               NVARCHAR (250)  NULL,
    [StatusChanged]                        INT             NULL,
    [StrategicInitiative]                  NVARCHAR (MAX)  NULL,
    [TargetCompletionDate]                 DATETIME        NULL,
    [TargetStartDate]                      DATETIME        NULL,
    [Technology]                           NVARCHAR (MAX)  NULL,
    [TechnologyAvailability]               NVARCHAR (MAX)  NULL,
    [TechnologyImpact]                     NVARCHAR (MAX)  NULL,
    [TechnologyIntegration]                NVARCHAR (MAX)  NULL,
    [TechnologyNotes1]                     NVARCHAR (MAX)  NULL,
    [TechnologyReliabilityChoice]          NVARCHAR (MAX)  NULL,
    [TechnologyRisk]                       NVARCHAR (MAX)  NULL,
    [TechnologySecurityChoice]             NVARCHAR (MAX)  NULL,
    [TechnologyUsabilityChoice]            NVARCHAR (MAX)  NULL,
    [TicketId]                             NVARCHAR (250)  NULL,
    [TotalConsultantHeadcount]             INT             NULL,
    [TotalConsultantHeadcountNotes]        NVARCHAR (MAX)  NULL,
    [TotalCost]                            INT             NULL,
    [TotalCostsNotes]                      NVARCHAR (MAX)  NULL,
    [TotalHoldDuration]                    INT             NULL,
    [TotalOffSiteConsultantHeadcount]      INT             NULL,
    [TotalOffSiteConsultantHeadcountNotes] NVARCHAR (MAX)  NULL,
    [TotalOnSiteConsultantHeadcount]       INT             NULL,
    [TotalOnSiteConsultantHeadcountNotes]  NVARCHAR (MAX)  NULL,
    [TotalStaffHeadcount]                  INT             NULL,
    [TotalStaffHeadcountNotes]             NVARCHAR (MAX)  NULL,
    [UserQuestionSummary]                  NVARCHAR (MAX)  NULL,
    [VendorLookup]                         BIGINT          NULL,
    [VendorName]                           NVARCHAR (250)  NULL,
    [VendorSupportChoice]                  NVARCHAR (MAX)  NULL,
    [WorkflowSkipStages]                   NVARCHAR (250)  NULL,
    [Title]                                VARCHAR (250)   NULL,
    [SharedServices]                       NVARCHAR (MAX)  NULL,
    [ResolvedByUser]                       NVARCHAR (250)  NULL,
    [ProjectConstraints]                   NVARCHAR (MAX)  NULL,
    [DataEditor]                           NVARCHAR (250)  NULL,
    [CostOfLabor]                          DECIMAL (18)    NULL,
    [ClosedByUser]                         NVARCHAR (250)  NULL,
    [ApplicationMultiLookup]               BIGINT          NULL,
    [TenantID]                             NVARCHAR (128)  NULL,
    [DataEditors]                          NVARCHAR (250)  DEFAULT ('') NULL,
    [Created]                              DATETIME        DEFAULT (getdate()) NOT NULL,
    [Modified]                             DATETIME        DEFAULT (getdate()) NOT NULL,
    [CreatedByUser]                        NVARCHAR (128)  DEFAULT ('00000000-0000-0000-0000-000000000000') NOT NULL,
    [ModifiedByUser]                       NVARCHAR (128)  DEFAULT ('00000000-0000-0000-0000-000000000000') NOT NULL,
    [Deleted]                              BIT             DEFAULT ((0)) NULL,
    [Attachments]                          NVARCHAR (2000) DEFAULT ('') NULL,
    [isAttachment]                         BIT             NULL,
    [ApproxContractValue]                  FLOAT (53)      NULL,
    [ProjectDuration]                      FLOAT (53)      NULL,
    [ResolutionDate]                       DATETIME        NULL,
    [ProjectClassLookup]                   BIGINT          NULL, 
    [PRPUser] NVARCHAR(128) NULL, 
    [ResolutionComments] NVARCHAR(MAX) NULL, 
	[ContributionToStrategyChoice]			NVARCHAR (250)  NULL,
	[PaybackCostSavingsChoice]				NVARCHAR (250)  NULL,
	[CustomerBenefitChoice]					NVARCHAR (250)  NULL,
	[RegulatoryChoice]						NVARCHAR (250)  NULL,
	[ITLifecycleRefreshChoice]				NVARCHAR (250)  NULL,
	[Age]                             BIGINT          NULL,
    [IconBlob] [varbinary](max) NULL,
    [ApprenticeArchitectUser]       NVARCHAR (MAX)  NULL,
	[ProjectAuditorUser]            NVARCHAR (MAX)  NULL,
    [ModuleName] VARCHAR(255) NULL, 
    [ApprovalDate] DATETIME NULL, 
    [ApprovedByUser] VARCHAR(128) NULL,
    [ProjectSummaryNote] VARCHAR(100) NULL, 
    [DepartmentLookup] BIGINT NULL, 
    CONSTRAINT [PK__NPR__3214EC27D4A354F7] PRIMARY KEY CLUSTERED ([ID] ASC),
    FOREIGN KEY ([FunctionalAreaLookup]) REFERENCES [dbo].[FunctionalAreas] ([ID]),
    FOREIGN KEY ([ImpactLookup]) REFERENCES [dbo].[Config_Module_Impact] ([ID]),
    FOREIGN KEY ([PriorityLookup]) REFERENCES [dbo].[Config_Module_Priority] ([ID]),
    FOREIGN KEY ([ProjectClassLookup]) REFERENCES [dbo].[Config_ProjectClass] ([ID]),
    FOREIGN KEY ([ProjectInitiativeLookup]) REFERENCES [dbo].[Config_ProjectInitiative] ([ID]),
    FOREIGN KEY ([RequestTypeLookup]) REFERENCES [dbo].[Config_Module_RequestType] ([ID]),
    FOREIGN KEY ([ServiceLookUp]) REFERENCES [dbo].[Config_Services] ([ID]),
    FOREIGN KEY ([SeverityLookup]) REFERENCES [dbo].[Config_Module_Severity] ([ID]),
    FOREIGN KEY ([VendorLookup]) REFERENCES [dbo].[Vendors] ([ID])
);


















GO

GO

GO

GO

GO

GO


GO

GO

GO

GO

GO
CREATE NONCLUSTERED INDEX [IX_NPR_PriorityLookup] ON [dbo].[NPR] ([AutoAdjustAllocations], [ModuleStepLookup], [PMMIdLookup], [VendorName], [PriorityLookup], [RequestTypeLookup], [Status], [TicketId])