CREATE TABLE [dbo].[Opportunity] (
    [ID]                             BIGINT          IDENTITY (1, 1) NOT NULL,
    [AcceptedDate]                   DATETIME        NULL,
    [ActualCompletionDate]           DATETIME        NULL,
    [ActualStartDate]                DATETIME        NULL,
    [AdditionalInfo]                 NVARCHAR (250)  NULL,
    [AdditionalRecipientsLookup]     NVARCHAR (2000) NULL,
    [Address]                        NVARCHAR (MAX)  NULL,
    [AnalysisDetails]                NVARCHAR (MAX)  NULL,
    [ApproxContractValue]            FLOAT (53)      NULL,
    [AssignedBy]                     NVARCHAR (MAX)  NULL,
    [AssistantProjectManagerUser]    NVARCHAR (MAX)  NULL,
    [Attachments]                    NVARCHAR (2000) CONSTRAINT [DF__Opportuni__Attac__2201B4CE] DEFAULT ('') NULL,
    [AutoAssign]                     BIT             NULL,
    [AwardedorLossDate]              DATETIME        NULL,
    [BidAmount]                      NVARCHAR (250)  NULL,
    [BidDueDate]                     DATETIME        NULL,
    [BusinessUnitLookup]             BIGINT          NULL,
    [CategoryLookup]                 BIGINT          NULL,
    [ChanceOfSuccessChoice]          NVARCHAR (MAX)  NULL,
    [City]                           NVARCHAR (250)  NULL,
    [Clarifications]                 NVARCHAR (MAX)  NULL,
    [ClientAcceptance]               BIT             NULL,
    [Closed]                         BIT             NULL,
    [CloseDate]                      DATETIME        NULL,
    [ClosedBy]                       NVARCHAR (128)  NULL,
    [ClosedDateOnly]                 DATETIME        NULL,
    [Comment]                        NVARCHAR (MAX)  NULL,
    [Competition]                    NVARCHAR (MAX)  NULL,
    [CompetitorName]                 NVARCHAR (250)  NULL,
    [ContactLookup]                  NVARCHAR (1000) NULL,
    [ContractedAmount]               NVARCHAR (250)  NULL,
    [Country]                        NVARCHAR (250)  NULL,
    [Created]                        DATETIME        CONSTRAINT [DF__Opportuni__Creat__22F5D907] DEFAULT (getdate()) NOT NULL,
    [CreatedByUser]                  NVARCHAR (128)  CONSTRAINT [DF__Opportuni__Creat__23E9FD40] DEFAULT ('00000000-0000-0000-0000-000000000000') NOT NULL,
    [CreationDate]                   DATETIME        NULL,
    [CRMBusinessUnitChoice]          NVARCHAR (128)  NULL,
    [CRMDuration]                    INT             NULL,
    [CRMOpportunityStatusChoice]     NVARCHAR (250)  NULL,
    [CurrentStageStartDate]          DATETIME        NULL,
    [DataEditors]                    NVARCHAR (250)  CONSTRAINT [DF__Opportuni__DataE__24DE2179] DEFAULT ('') NULL,
    [DecisionDate]                   DATETIME        NULL,
    [Deleted]                        BIT             CONSTRAINT [DF__Opportuni__Delet__25D245B2] DEFAULT ((0)) NULL,
    [DepartmentLookup]               BIGINT          NULL,
    [Description]                    NVARCHAR (MAX)  NULL,
    [Description1]                   NVARCHAR (MAX)  NULL,
    [DesiredCompletionDate]          DATETIME        NULL,
    [DivisionLookup]                 BIGINT          NULL,
    [DocumentLibraryName]            NVARCHAR (250)  NULL,
    [DueDate]                        DATETIME        NULL,
    [EmailAddress]                   NVARCHAR (250)  NULL,
    [EstimatedConstructionEnd]       DATETIME        NULL,
    [EstimatedConstructionStart]     DATETIME        NULL,
    [EstimatorUser]                  NVARCHAR (MAX)  NULL,
    [Fee]                            NVARCHAR (250)  NULL,
    [FunctionalAreaLookup]           BIGINT          NULL,
    [GoNoGo]                         BIT             NULL,
    [HardCopyDeadline]               DATETIME        NULL,
    [History]                        NVARCHAR (MAX)  NULL,
    [ImpactLookup]                   BIGINT          NULL,
    [InitiatorUser]                  NVARCHAR (MAX)  NULL,
    [Insurance]                      NVARCHAR (250)  NULL,
    [InterviewDate]                  DATETIME        NULL,
    [IsLead]                         BIT             NULL,
    [IsPrivate]                      BIT             NULL,
    [JobWalkthroughDate]             DATETIME        NULL,
    [LeadLevelChoice]                NVARCHAR (250)  NULL,
    [LEMIdLookup]                    NVARCHAR (250)  NULL,
    [ManagerApprovalNeeded]          BIT             NULL,
    [MarketSector]                   NVARCHAR (250)  NULL,
    [Modified]                       DATETIME        CONSTRAINT [DF__Opportuni__Modif__26C669EB] DEFAULT (getdate()) NOT NULL,
    [ModifiedByUser]                 NVARCHAR (128)  CONSTRAINT [DF__Opportuni__Modif__27BA8E24] DEFAULT ('00000000-0000-0000-0000-000000000000') NOT NULL,
    [ModuleStepLookup]               BIGINT          NULL,
    [Note]                           NVARCHAR (MAX)  NULL,
    [OnHoldReasonChoice]             NVARCHAR (MAX)  NULL,
    [OnHoldStartDate]                DATETIME        NULL,
    [OnHoldTillDate]                 DATETIME        NULL,
    [OpportunitySize]                NVARCHAR (250)  NULL,
    [OpportunityTypeChoice]          NVARCHAR (250)  NULL,
    [ORPUser]                        NVARCHAR (MAX)  NULL,
    [OwnerUser]                      NVARCHAR (MAX)  NULL,
    [PctComplete]                    INT             NULL,
    [PreconStartDate]                DATETIME        NULL,
    [PreparedBy]                     NVARCHAR (MAX)  NULL,
    [ProjectExecutiveUser]           NVARCHAR (MAX)  NULL,
    [ProjectManagerUser]             NVARCHAR (250)  NULL,
    [ProjectName]                    NVARCHAR (250)  NULL,
    [ProposalAmount]                 NVARCHAR (250)  NULL,
    [ProposalDate]                   DATETIME        NULL,
    [ProposalDeadline]               DATETIME        NULL,
    [ProposalRecipientLookup]        NVARCHAR (2000) NULL,
    [ProposalSquareFootage]          NVARCHAR (250)  NULL,
    [PRPUser]                        NVARCHAR (MAX)  NULL,
    [PRPGroupUser]                   NVARCHAR (MAX)  NULL,
    [QuestionDueDate]                DATETIME        NULL,
    [Reason]                         NVARCHAR (500)  NULL,
    [RequestTypeCategory]            NVARCHAR (250)  NULL,
    [RequestTypeLookup]              BIGINT          NULL,
    [ResolutionTypeChoice]           NVARCHAR (MAX)  NULL,
    [ResolvedBy]                     NVARCHAR (MAX)  NULL,
    [ReSubmissionDate]               DATETIME        NULL,
    [RetailSqft]                     NVARCHAR (250)  NULL,
    [RetailSqftNum]                  INT             NULL,
    [RFPType]                        NVARCHAR (250)  NULL,
    [ServiceLookUp]                  BIGINT          NULL,
    [SignedNDA]                      BIT             NULL,
    [StageActionUsersUser]           NVARCHAR (MAX)  NULL,
    [StageActionUserTypes]           NVARCHAR (250)  NULL,
    [StageStep]                      INT             NULL,
    [StartDate]                      DATETIME        NULL,
    [StateLookup]                    BIGINT          NULL,
    [Status]                         NVARCHAR (250)  NULL,
    [StatusChanged]                  INT             NULL,
    [StreetAddress1]                 NVARCHAR (250)  NULL,
    [SubCategoryLookup]              BIGINT          NULL,
    [SubmissionDate]                 DATETIME        NULL,
    [SuperintendentUser]             NVARCHAR (MAX)  NULL,
    [TargetCompletionDate]           DATETIME        NULL,
    [TargetStartDate]                DATETIME        NULL,
    [Telephone]                      NVARCHAR (250)  NULL,
    [TenantID]                       NVARCHAR (128)  NULL,
    [TicketId]                       NVARCHAR (250)  NULL,
    [OnHold]                         INT             NULL,
    [Title]                          NVARCHAR (250)  NULL,
    [TotalHoldDuration]              INT             NULL,
    [UsableSqFt]                     NVARCHAR (250)  NULL,
    [UsableSqFtNum]                  INT             NULL,
    [WeeklyGeneralConditions]        NVARCHAR (250)  NULL,
    [WELL]                           BIGINT          NULL,
    [WELLLevelsChoice]               NVARCHAR (250)  NULL,
    [WorkDescription]                NVARCHAR (MAX)  NULL,
    [WorkflowSkipStages]             NVARCHAR (250)  NULL,
    [WorkflowType]                   BIGINT          NULL,
    [Zip]                            NVARCHAR (250)  NULL,
    [PriorityLookup]                 BIGINT          NULL,
    [RankingCriteriaTotal]           NVARCHAR (5)    DEFAULT ((0)) NULL,
    [DataMigrationID]                INT             NULL,
    [SuccessChance]                  NVARCHAR (250)  NULL,
    [CRMProjectComplexityChoice]     NVARCHAR(10)             NULL,
    [SectorChoice]					 NVARCHAR (250)  NULL,
    [APMUser]                        NVARCHAR (MAX)  NULL,
    [PreConstruction]                NVARCHAR (MAX)  NULL,
    [CRMUser]                        NVARCHAR (MAX)  NULL,
    [CRMAdminUser]                   NVARCHAR (MAX)  NULL,
    [PreConAdminUser]                NVARCHAR (MAX)  NULL,
    [ProjectEngineerUser]            NVARCHAR (MAX)  NULL,
    [FieldOperationsManagerUser]     NVARCHAR (MAX)  NULL,
    [SafetyManagerUser]              NVARCHAR (MAX)  NULL,
    [QualityControlCoordinatorUser]  NVARCHAR (MAX)  NULL,
    [FieldEngineerUser]              NVARCHAR (MAX)  NULL,
    [CarpenterUser]                  NVARCHAR (MAX)  NULL,
    [CarpenterApprenticeUser]        NVARCHAR (MAX)  NULL,
    [CarpenterForemanUser]           NVARCHAR (MAX)  NULL,
    [AssistantSuperintendentUser]    NVARCHAR (MAX)  NULL,
    [LaborerSuperintendentUser]      NVARCHAR (MAX)  NULL,
    [LaborerForemanUser]             NVARCHAR (MAX)  NULL,
    [LaborerUser]                    NVARCHAR (MAX)  NULL,
    [ArchitectUser]                  NVARCHAR (MAX)  NULL,
    [BusinessDevelopmentManagerUser] NVARCHAR (MAX)  NULL,
    [ManagerServiceGroupUser]        NVARCHAR (MAX)  NULL,
    [MEPCoordinatorUser]             NVARCHAR (MAX)  NULL,
    [ProgramManagerUser]             NVARCHAR (MAX)  NULL,
    [ProjectManagerArchitectureUser] NVARCHAR (MAX)  NULL,
    [ProjectManagerServiceGroupUser] NVARCHAR (MAX)  NULL,
    [SeniorManagerAccountingUser]    NVARCHAR (MAX)  NULL,
    [ServiceCoordinatorUser]         NVARCHAR (MAX)  NULL,
    [SustainbilityAssociateUser]     NVARCHAR (MAX)  NULL,
    [SustainbilityCoordinatorUser]   NVARCHAR (MAX)  NULL,
    [ProjectId]                      NVARCHAR (255)  NULL,
    [CRMUrgencyChoice]               NVARCHAR (255)  NULL,
    [OwnerContractTypeChoice]        NVARCHAR (255)  NULL,
    [StudioChoice]                   NVARCHAR (255)  NULL,
	[CRMCompanyLookup]               NVARCHAR (250)  NULL,
	[PreconEndDate]					 DATETIME        NULL,
	[ExternalID]					 NVARCHAR (MAX)  NULL,
	[SalesforceLeadPriority]		 NVARCHAR(1000)  NULL,
	[PreconLeadUser]			  	 NVARCHAR (MAX)  NULL,
	[IconBlob]							varbinary(max) NULL,
    [ERPJobID]  nvarchar(500) NULL,
    [ApprenticeArchitectUser]       NVARCHAR (MAX)  NULL,
	[ProjectAuditorUser]            NVARCHAR (MAX)  NULL,
	[Change_Orders]  nvarchar(255) NULL,
	[SubContract]  nvarchar(255) NULL,
	[Approved_SCO]  nvarchar(255) NULL,
	[Resource_Costs]   nvarchar(255) NULL,
	[Resource_Util]    nvarchar(255) NULL,
	[OCOs]   int NULL,
	[SCOs]    int NULL,
	[Submittals]    int NULL,
	[Drawings]   int NULL,
	[Action_Items]   int NULL,
	[GrossP]          nvarchar(255) NULL,
	[GrossD]           nvarchar(255) NULL,
	[Real_Income]       nvarchar(255) NULL,
	[ProjectRisk]       int NULL,
	[ProjectComplexityScore]     float NULL,
	[ProjectValue]        int NULL,
	[ProjectSimilarity]       int NULL,
	[ProjectReview]         int NULL,
	[DivisionChoice]         varchar(max) NULL,
	[RFIs]     int NULL,
    [EnableStdWorkItems] BIT NULL, 
    [FeePct] decimal(6,2) NULL,
    [CloseoutDate] DATETIME NULL,
    [ReopenCount] INT NULL, 
    [ERPJobIDNC]    nvarchar(500) NULL,
    [ApprovalDate] DATETIME NULL, 
    [ApprovedByUser] VARCHAR(MAX) NULL,
    [OpportunityTargetChoice] NVARCHAR(MAX) Default(('CPR')),
    [HasPreconstructionContract] BIT DEFAULT 0,
    [ProjectLeadUser] NVARCHAR(MAX) NULL,
    [LeadEstimatorUser] NVARCHAR(MAX) NULL,
    [LeadSuperintendentUser] NVARCHAR(MAX) NULL,
    [ShortName] VARCHAR(20) NULL, 
    CONSTRAINT [PK__Opportun__3214EC27BF66ADA0] PRIMARY KEY CLUSTERED ([ID] ASC)
);












GO

GO

GO

GO

GO

GO

GO

GO

GO

GO
