CREATE TABLE [dbo].[PMM_Archive] (
    [ID]                            BIGINT          IDENTITY (1, 1) NOT NULL,
    [ActualCompletionDate]          DATETIME        NULL,
    [ActualHour]                    INT             NULL,
    [ActualStartDate]               DATETIME        NULL,
    [ApprovedRFE]                   NVARCHAR (250)  NULL,
    [ApprovedRFEAmount]             NVARCHAR (250)  NULL,
    [ApprovedRFEType]               NVARCHAR (MAX)  NULL,
    [APPTitleLookup]                BIGINT          NULL,
    [ArchitectureScore]             INT             NULL,
    [ArchitectureScoreNotes]        NVARCHAR (MAX)  NULL,
    [AutoAdjustAllocations]         BIT             NULL,
    [BeneficiariesLookup]           NVARCHAR (250)  NULL,
    [BenefitsExperienced]           NVARCHAR (MAX)  NULL,
    [BreakevenMonth]                NVARCHAR (250)  NULL,
    [BusinessManagerUser]           NVARCHAR (MAX)  NULL,
    [ClassificationChoice]          NVARCHAR (MAX)  NULL,
    [ClassificationImpact]          NVARCHAR (MAX)  NULL,
    [ClassificationTypeChoice]      NVARCHAR (MAX)  NULL,
    [Closed]                        BIT             NULL,
    [CloseDate]                     DATETIME        NULL,
    [Comment]                       NVARCHAR (MAX)  NULL,
    [CompanyMultiLookup]            BIGINT          NULL,
    [ConstraintNotes]               NVARCHAR (MAX)  NULL,
    [CreationDate]                  DATETIME        NULL,
    [CurrentStageStartDate]         DATETIME        NULL,
    [CustomUGChoice01]              NVARCHAR (MAX)  NULL,
    [CustomUGChoice02]              NVARCHAR (MAX)  NULL,
    [CustomUGChoice03]              NVARCHAR (MAX)  NULL,
    [CustomUGChoice04]              NVARCHAR (MAX)  NULL,
    [CustomUGDate01]                DATETIME        NULL,
    [CustomUGDate02]                DATETIME        NULL,
    [CustomUGDate03]                DATETIME        NULL,
    [CustomUGDate04]                DATETIME        NULL,
    [CustomUGText01]                NVARCHAR (250)  NULL,
    [CustomUGText02]                NVARCHAR (250)  NULL,
    [CustomUGText03]                NVARCHAR (250)  NULL,
    [CustomUGText04]                NVARCHAR (250)  NULL,
    [CustomUGText05]                NVARCHAR (250)  NULL,
    [CustomUGText06]                NVARCHAR (250)  NULL,
    [CustomUGText07]                NVARCHAR (250)  NULL,
    [CustomUGText08]                NVARCHAR (250)  NULL,
    [CustomUGUser01]                NVARCHAR (MAX)  NULL,
    [CustomUGUser02]                NVARCHAR (MAX)  NULL,
    [CustomUGUser03]                NVARCHAR (MAX)  NULL,
    [CustomUGUser04]                NVARCHAR (MAX)  NULL,
    [CustomUGUserMulti01]           NVARCHAR (250)  NULL,
    [CustomUGUserMulti02]           NVARCHAR (250)  NULL,
    [CustomUGUserMulti03]           NVARCHAR (250)  NULL,
    [CustomUGUserMulti04]           NVARCHAR (250)  NULL,
    [DaysToComplete]                INT             NULL,
    [Description]                   NVARCHAR (MAX)  NULL,
    [DesiredCompletionDate]         DATETIME        NULL,
    [DivisionMultiLookup]           BIGINT          NULL,
    [Duration]                      INT             NULL,
    [EliminatesStaffHeadCount]      NVARCHAR (250)  NULL,
    [EstimatedHours]                INT             NULL,
    [EstimatedRemainingHours]       INT             NULL,
    [EstProjectSpend]               NVARCHAR (250)  NULL,
    [EstProjectSpendComment]        NVARCHAR (MAX)  NULL,
    [FunctionalAreaLookup]          BIGINT          NULL,
    [History]                       NVARCHAR (MAX)  NULL,
    [ImpactAsImprovesRevenues]      NVARCHAR (250)  NULL,
    [ImpactAsOperationalEfficiency] NVARCHAR (250)  NULL,
    [ImpactAsSaveMoney]             NVARCHAR (250)  NULL,
    [ImpactLookup]                  BIGINT          NULL,
    [InitiatorUser]                 NVARCHAR (MAX)  NULL,
    [IsPrivate]                     BIT             NULL,
    [ITManagerUser]                     NVARCHAR (MAX)  NULL,
    [LessonsLearned]                NVARCHAR (MAX)  NULL,
    [LocationMultLookup]            BIGINT          NULL,
    [ModuleNameLookup]              NVARCHAR (250)  NULL,
    [ModuleStepLookup]              NVARCHAR (250)  NULL,
    [NextActivity]                  NVARCHAR (250)  NULL,
    [NextMilestone]                 NVARCHAR (250)  NULL,
    [NoOfConsultants]               INT             NULL,
    [NoOfConsultantsNotes]          NVARCHAR (MAX)  NULL,
    [NoOfFTEs]                      INT             NULL,
    [NoOfFTEsNotes]                 NVARCHAR (MAX)  NULL,
    [NPRIdLookup]                   BIGINT          NULL,
    [OnHold]                        INT             NULL,
    [OnHoldReasonChoice]            NVARCHAR (MAX)  NULL,
    [OnHoldTillDate]                DATETIME        NULL,
    [OwnerUser]                     NVARCHAR (250)  NULL,
    [PctComplete]                   Float             NULL,
    [PriorityLookup]                BIGINT          NULL,
    [ProblemBeingSolved]            NVARCHAR (MAX)  NULL,
    [ProjectAssumptions]            NVARCHAR (MAX)  NULL,
    [ProjectBenefits]               NVARCHAR (MAX)  NULL,
    [ProjectClassLookup]            BIGINT          NULL,
    [ProjectCost]                   INT             NULL,
    [ProjectCostNote]               NVARCHAR (MAX)  NULL,
    [ProjectInitiativeLookup]       BIGINT          NULL,
    [ProjectIteration]              INT             NULL,
    [ProjectLifeCycleLookup]        BIGINT          NULL,
    [ProjectManagerUser]            NVARCHAR (250)  NULL,
    [ProjectPhasePctComplete]       INT             NULL,
    [ProjectRank]                   NVARCHAR (250)  NULL,
    [ProjectRank2]                  NVARCHAR (250)  NULL,
    [ProjectRank3]                  NVARCHAR (250)  NULL,
    [ProjectRiskNotes]              NVARCHAR (MAX)  NULL,
    [ProjectScheduleNote]           NVARCHAR (MAX)  NULL,
    [ProjectScope]                  NVARCHAR (MAX)  NULL,
    [ProjectScore]                  NVARCHAR (250)  NULL,
    [ProjectScoreNotes]             NVARCHAR (MAX)  NULL,
    [ProjectStatus]                 NVARCHAR (MAX)  NULL,
    [ProjectSummaryNote]            NVARCHAR (MAX)  NULL,
    [PRPGroupUser]                  NVARCHAR (MAX)  NULL,
    [RequestorUser]                 NVARCHAR (250)  NULL,
    [RequestTypeCategory]           NVARCHAR (250)  NULL,
    [RequestTypeLookup]             BIGINT          NULL,
    [RequestTypeSubCategory]        NVARCHAR (250)  NULL,
    [RiskScore]                     INT             NULL,
    [RiskScoreNotes]                NVARCHAR (MAX)  NULL,
    [ROI]                           NVARCHAR (250)  NULL,
    [ScrumLifeCycle]                BIT             NULL,
    [ServiceLookUp]                 BIGINT          NULL,
    [SeverityLookup]                BIGINT          NULL,
    [ShowProjectStatus]             BIT             NULL,
    [SponsorsUser]                  NVARCHAR (250)  NULL,
    [SprintDuration]                INT             NULL,
    [StageActionUsersUser]          NVARCHAR (250)  NULL,
    [StageActionUserTypes]          NVARCHAR (250)  NULL,
    [StageStep]                     INT             NULL,
    [StakeHoldersUser]              NVARCHAR (250)  NULL,
    [Status]                        NVARCHAR (250)  NULL,
    [StatusChanged]                 INT             NULL,
    [TargetCompletionDate]          DATETIME        NULL,
    [TargetStartDate]               DATETIME        NULL,
    [TicketId]                      NVARCHAR (250)  NULL,
    [TotalConsultantHeadcount]      INT             NULL,
    [TotalConsultantHeadcountNotes] NVARCHAR (MAX)  NULL,
    [TotalCost]                     INT             NULL,
    [TotalCostsNotes]               NVARCHAR (MAX)  NULL,
    [TotalStaffHeadcount]           INT             NULL,
    [TotalStaffHeadcountNotes]      NVARCHAR (MAX)  NULL,
    [WorkflowSkipStages]            NVARCHAR (250)  NULL,
    [Title]                         VARCHAR (250)   NULL,
    [ApplicationMultiLookup]        BIGINT          NULL,
    [ClosedByUser]                  NVARCHAR (250)  NULL,
    [DataEditor]                    NVARCHAR (250)  NULL,
    [ResolvedByUser]                NVARCHAR (250)  NULL,
    [SharedServices]                NVARCHAR (MAX)  NULL,
    [TotalActualHours]              INT             NULL,
    [TenantID]                      NVARCHAR (128)  NULL,
    [DataEditors]                   NVARCHAR (250)  DEFAULT ('') NULL,
    [Created]                       DATETIME        DEFAULT (getdate()) NOT NULL,
    [Modified]                      DATETIME        DEFAULT (getdate()) NOT NULL,
    [CreatedByUser]                 NVARCHAR (128)  DEFAULT ('00000000-0000-0000-0000-000000000000') NOT NULL,
    [ModifiedByUser]                NVARCHAR (128)  DEFAULT ('00000000-0000-0000-0000-000000000000') NOT NULL,
    [Deleted]                       BIT             DEFAULT ((0)) NULL,
    [Attachments]                   NVARCHAR (2000) DEFAULT ('') NULL,
	[ProjectComplexityChoice]       NVARCHAR(MAX)             NULL,
    [ProjectDuration]               FLOAT (53)      DEFAULT ((0)) NULL,
    [ApproxContractValue]           FLOAT (53)      NULL,
    [ProjectEstSizeMinHrs]          INT             NULL,
    [ProjectEstSizeMaxHrs]          INT             NULL,
    [ProjectEstDurationMinDays]     INT             NULL,
    [ProjectEstDurationMaxDays]     INT             NULL,
    [AdoptionRiskChoice]            NVARCHAR (MAX)  NULL,
    [VendorSupportChoice]           NVARCHAR (MAX)  NULL,
    [InternalCapabilityChoice]      NVARCHAR (MAX)  NULL,
    [TechnologySecurityChoice]      NVARCHAR (MAX)  NULL,
    [TechnologyUsabilityChoice]     NVARCHAR (MAX)  NULL,
    [TechnologyReliabilityChoice]   NVARCHAR (MAX)  NULL,
    [OrganizationalImpactChoice]    NVARCHAR (MAX)  NULL,
    [ClassificationScopeChoice]     NVARCHAR (MAX)  NULL,
    [ClassificationSizeChoice]      NVARCHAR (MAX)  NULL,
    [NextMilestoneDate]             DATETIME2 (7)   NULL,
    [ProjectCoordinators]           NVARCHAR (MAX)  NULL,
    [ResolutionDate]                DATETIME        NULL,
    [PRPUser] NVARCHAR(128) NULL, 
    [ORPUser] NVARCHAR(128) NULL, 
	[Age]                             BIGINT          NULL,
	[BreakEvenIn] int null,
	[ClassificationNotes] nvarchar(max) null,
	[EliminatesHeadcount] int null,
	[ImpactBusinessGrowthChoice] nvarchar(max) null,
	[ImpactDecisionMakingChoice] nvarchar(max) null,
	[ImpactIncreasesProductivityChoice] nvarchar(max) null,
	[ImpactReducesExpensesChoice] nvarchar(max) null,
	[ImpactReducesRiskChoice] nvarchar(max) null,
	[ImpactRevenueIncreaseChoice] nvarchar(max) null,
	[IsITGApprovalRequired] bit null,
	[IsSteeringApprovalRequired] bit null,
	[OtherDescribe] nvarchar(max) null,
	[ContributionToStrategyChoice] nvarchar(250) null,
	[PaybackCostSavingsChoice] nvarchar(250) null,
	[CustomerBenefitChoice] nvarchar(250) null,
	[RegulatoryChoice] nvarchar(250) null,
	[ITLifecycleRefreshChoice] nvarchar(250) null,
    [IconBlob] [varbinary](max) NULL,
    [ApprenticeArchitectUser]       NVARCHAR (MAX)  NULL,
	[ProjectAuditorUser]            NVARCHAR (MAX)  NULL,
    [ModuleName] VARCHAR(255) NULL, 
    [ApprovalDate] DATETIME NULL, 
    [ApprovedByUser] VARCHAR(128) NULL,
    CONSTRAINT [PKK_PMM] PRIMARY KEY CLUSTERED ([ID] ASC),
    FOREIGN KEY ([FunctionalAreaLookup]) REFERENCES [dbo].[FunctionalAreas] ([ID]),
    FOREIGN KEY ([ImpactLookup]) REFERENCES [dbo].[Config_Module_Impact] ([ID]),
    FOREIGN KEY ([PriorityLookup]) REFERENCES [dbo].[Config_Module_Priority] ([ID]),
    FOREIGN KEY ([ProjectClassLookup]) REFERENCES [dbo].[Config_ProjectClass] ([ID]),
    FOREIGN KEY ([ProjectInitiativeLookup]) REFERENCES [dbo].[Config_ProjectInitiative] ([ID]),
    FOREIGN KEY ([ProjectLifeCycleLookup]) REFERENCES [dbo].[Config_ModuleLifeCycles] ([ID]),
    FOREIGN KEY ([RequestTypeLookup]) REFERENCES [dbo].[Config_Module_RequestType] ([ID]),
    FOREIGN KEY ([ServiceLookUp]) REFERENCES [dbo].[Config_Services] ([ID]),
    FOREIGN KEY ([SeverityLookup]) REFERENCES [dbo].[Config_Module_Severity] ([ID])
);














GO

GO

GO

GO

GO

GO

GO

GO

GO

GO

GO

GO
