CREATE TABLE [dbo].[ResourceUtilizationSummary]
(
	
	[ItemOrder] [int] NULL,
	[FullAllocation] [varchar](10) NULL,
	[Id] [varchar](max) NULL,
	[IncludeAllResources] [varchar](10) NULL,
	[ResourceUser] [varchar](1000) NULL,
	[ProjectCapacity] [varchar](1000) NULL,
	[RevenueCapacity] [varchar](1000) NULL,
	[#LifeTime] [varchar](1000) NULL,
	[$LifeTime] [varchar](1000) NULL,
	[ResourceUserAllocated] [varchar](1000) NULL,
	[Jan] [varchar](max) NULL,
	[Feb] [varchar](max) NULL,
	[Mar] [varchar](max) NULL,
	[Apr] [varchar](max) NULL,
	[May] [varchar](max) NULL,
	[Jun] [varchar](max) NULL,
	[Jul] [varchar](max) NULL,
	[Aug] [varchar](max) NULL,
	[Sep] [varchar](max) NULL,
	[Oct] [varchar](max) NULL,
	[Nov] [varchar](max) NULL,
	[Dec] [varchar](max) NULL,
	[FlagType] [varchar](20) NULL,
	[Year] [varchar](5) NULL,
	[TenantID] [varchar](max) NULL,
	[DepartmentLookup] [varchar](100) NULL,
	[Role] [varchar](max) NULL,
	[ManagerUser] [varchar](max) NULL,
	[LevelName] [varchar](1000) NULL,
	[ClosedProjects] [varchar](10)  NULL,
	[Filter] nvarchar(250) NULL,
	[Studio] nvarchar(250) NULL,
	[Division] bigint NULL,
	[Sector] nvarchar(250) NULL
)

