CREATE TABLE [dbo].[ResourceUtilizationSummaryFooter]
(
	ResourceUser varchar(max),
	UGITStartDate datetime,
	UGITEndDate datetime,
	Enabled bit,
	DepartmentLookup varchar(10),
	GlobalRoleID varchar(max),
	IsManager bit,
	IsRole bit,
	TenantID varchar(max),
	ManagerUser varchar(max),
	JobProfile varchar(1000),
	ModuleNameLookup varchar(max),
	ResourceUserAllocated varchar(max),
	Jan varchar(10),
	Feb varchar(10),
	Mar varchar(10),
	Apr varchar(10),
	May varchar(10),
	Jun varchar(10),
	Jul varchar(10),
	Aug varchar(10),
	Sep varchar(10),
	Oct varchar(10),
	Nov varchar(10),
	Dec varchar(10),
	Year varchar(4)
)
