CREATE TABLE [dbo].[SVCRequests_Archive] (
    [ID]                      BIGINT          IDENTITY (1, 1) NOT NULL,
    [ActualCompletionDate]    DATETIME        NULL,
    [ActualHours]             INT             NULL,
    [ActualStartDate]         DATETIME        NULL,
    [ApproverUser]            NVARCHAR (250)  NULL,
    [Closed]                  BIT             NULL,
    [CloseDate]               DATETIME        NULL,
    [Comment]                 NVARCHAR (MAX)  NULL,
    [CreationDate]            DATETIME        NULL,
    [CurrentStageStartDate]   DATETIME        NULL,
    [Description]             NVARCHAR (MAX)  NULL,
    [DesiredCompletionDate]   DATETIME        NULL,
    [EstimatedHours]          INT             NULL,
    [History]                 NVARCHAR (MAX)  NULL,
    [InitiatorUser]           NVARCHAR (MAX)  NULL,
    [IsAllTaskComplete]       BIT             NULL,
    [IsPrivate]               BIT             NULL,
    [ModuleStepLookup]        NVARCHAR (250)  NULL,
    [OnHold]                  INT             NULL,
    [OnHoldReasonChoice]      NVARCHAR (MAX)  NULL,
    [OnHoldTillDate]          DATETIME        NULL,
    [OwnerUser]               NVARCHAR (250)  NULL,
    [OwnerApprovalRequired]   BIT             NULL,
    [PctComplete]             INT             NULL,
    [PriorityLookup]          BIGINT          NULL,
    [ProjectClassLookup]      BIGINT          NULL,
    [ProjectInitiativeLookup] BIGINT          NULL,
    [RequestorUser]           NVARCHAR (250)  NULL,
    [RequestTypeCategory]     NVARCHAR (250)  NULL,
    [RequestTypeLookup]       BIGINT          NULL,
    [RequestTypeSubCategory]  NVARCHAR (250)  NULL,
    [ServiceLookUp]           BIGINT          NULL,
    [ShowProjectStatus]       BIT             NULL,
    [StageActionUsersUser]    NVARCHAR (250)  NULL,
    [StageActionUserTypes]    NVARCHAR (250)  NULL,
    [StageStep]               INT             NULL,
    [Status]                  NVARCHAR (250)  NULL,
    [StatusChanged]           INT             NULL,
    [TargetCompletionDate]    DATETIME        NULL,
    [TargetStartDate]         DATETIME        NULL,
    [TicketId]                NVARCHAR (250)  NULL,
    [UserQuestionSummary]     NVARCHAR (MAX)  NULL,
    [WorkflowSkipStages]      NVARCHAR (250)  NULL,
    [Title]                   VARCHAR (250)   NULL,
    [TenantID]                NVARCHAR (128)  NULL,
    [DataEditors]             NVARCHAR (250)  DEFAULT ('') NULL,
    [Created]                 DATETIME        DEFAULT (getdate()) NOT NULL,
    [Modified]                DATETIME        DEFAULT (getdate()) NOT NULL,
    [CreatedByUser]           NVARCHAR (128)  DEFAULT ('00000000-0000-0000-0000-000000000000') NOT NULL,
    [ModifiedByUser]          NVARCHAR (128)  DEFAULT ('00000000-0000-0000-0000-000000000000') NOT NULL,
    [Deleted]                 BIT             DEFAULT ((0)) NULL,
    [Attachments]             NVARCHAR (2000) DEFAULT ('') NULL,
    [SLADisabled]             BIT             DEFAULT ((0)) NOT NULL,
    [OnHoldStartDate]         DATETIME2 (7)   NULL,
    [TotalHoldDuration]       INT             NULL,
    [isAttachment]            BIT             DEFAULT ((0)) NULL,
    [PRPUser]                 NVARCHAR (MAX)  NULL,
    [DataMigrationID]         INT             NULL,
    [ApprovalDate] DATETIME NULL, 
    [ApprovedByUser] VARCHAR(128) NULL,
    CONSTRAINT [PK__SVCReque_Archive__3214EC27FCE356CA] PRIMARY KEY CLUSTERED ([ID] ASC)
);

