 
 

/* For Hours Columns*/
ALTER TABLE dbo.INC ALTER COLUMN ActualHours Float;
ALTER TABLE dbo.INC ALTER COLUMN OutageHours Float;
ALTER TABLE dbo.ModuleTasks ALTER COLUMN ActualHours Float; -- Done
ALTER TABLE dbo.ModuleTasks ALTER COLUMN EstimatedRemainingHours Float;--Done
ALTER TABLE dbo.ModuleTasks ALTER COLUMN EstimatedHours Float;--Done
ALTER TABLE dbo.Config_Module_RequestType ALTER COLUMN EstimatedHours Float;--Done
ALTER TABLE dbo.ModuleStageConstraintTemplates ALTER COLUMN TaskActualHours Float;--Done
ALTER TABLE dbo.ModuleStageConstraintTemplates ALTER COLUMN EstimatedHours Float;--Done
ALTER TABLE dbo.Resources ALTER COLUMN EstimatedHours Float;--Done
ALTER TABLE dbo.DRQ_Archive ALTER COLUMN ActualHours Float;--Done
ALTER TABLE dbo.DRQ_Archive ALTER COLUMN EstimatedHours Float;--Done
ALTER TABLE dbo.DRQ_Archive ALTER COLUMN OutageHours Float;--Done
ALTER TABLE dbo.Config_Module_SLARule ALTER COLUMN SLAHours Float;--Done
ALTER TABLE dbo.ResourceTimeSheet ALTER COLUMN HoursTaken Float;--Done
ALTER TABLE dbo.DashboardSummary ALTER COLUMN ActualHours Float;--Done
ALTER TABLE dbo.TSK ALTER COLUMN EstimatedHours Float;--Done
ALTER TABLE dbo.TSK ALTER COLUMN EstimatedRemainingHours Float;--Done
ALTER TABLE dbo.TSK ALTER COLUMN ActualHours Float;--Done
ALTER TABLE dbo.PMMIssues ALTER COLUMN TaskActualHours Float;--Done
ALTER TABLE dbo.PMMIssues ALTER COLUMN TaskEstimatedHours Float;--Done
ALTER TABLE dbo.TicketHours ALTER COLUMN HoursTaken Float;--Done
ALTER TABLE dbo.Sprint ALTER COLUMN RemainingHours Float;--Done
ALTER TABLE dbo.Sprint ALTER COLUMN TaskEstimatedHours Float;--Done
ALTER TABLE dbo.PMMIssuesHistory ALTER COLUMN TaskActualHours Float;--Done
ALTER TABLE dbo.PMMIssuesHistory ALTER COLUMN TaskEstimatedHours Float;--Done
ALTER TABLE dbo.RCA ALTER COLUMN ActualHours Float;--Done
ALTER TABLE dbo.ProjectSummaryPage ALTER COLUMN ResouceHoursBilled Float;--Done
ALTER TABLE dbo.ProjectSummaryPage ALTER COLUMN ResourceHoursPrecon Float;--Done
ALTER TABLE dbo.ProjectSummaryPage ALTER COLUMN ResourceHoursBilledtoDate Float;--Done
ALTER TABLE dbo.ProjectSummaryPage ALTER COLUMN ResourceHoursActual Float;--Done
ALTER TABLE dbo.ProjectSummaryPage ALTER COLUMN ResourceHoursRemaining Float;--Done
ALTER TABLE dbo.ProjectSummaryPage ALTER COLUMN TotalResourceHours Float;--Done
ALTER TABLE dbo.SprintSummary ALTER COLUMN RemainingHours Float;--Done
ALTER TABLE dbo.SprintSummary ALTER COLUMN TaskEstimatedHours Float;--Done
ALTER TABLE dbo.Contracts_Archive ALTER COLUMN EstimatedHours Float;--Done
ALTER TABLE dbo.NPR ALTER COLUMN EstimatedHours Float;--Done
ALTER TABLE dbo.NPR ALTER COLUMN ActualHours Float;--Done
ALTER TABLE dbo.PMM_Archive ALTER COLUMN EstimatedHours Float;--Done
ALTER TABLE dbo.PMM_Archive ALTER COLUMN EstimatedRemainingHours Float;--Done
ALTER TABLE dbo.PMM_Archive ALTER COLUMN TotalActualHours Float;--Done
ALTER TABLE dbo.AssetVendors ALTER COLUMN SupportHours Float;--Done
ALTER TABLE dbo.SprintTasks ALTER COLUMN TaskActualHours Float;--Done
ALTER TABLE dbo.SprintTasks ALTER COLUMN TaskEstimatedHours Float;--Done
ALTER TABLE dbo.NPR_Archive ALTER COLUMN EstimatedHours Float;--Done
ALTER TABLE dbo.NPR_Archive ALTER COLUMN ActualHours Float;--Done
ALTER TABLE dbo.TaskTemplateItems ALTER COLUMN TaskActualHours Float;--Done
ALTER TABLE dbo.TaskTemplateItems ALTER COLUMN TaskEstimatedHours Float;--Done
ALTER TABLE dbo.PMMTasks ALTER COLUMN EstimatedRemainingHours Float;--Done
ALTER TABLE dbo.PMMTasks ALTER COLUMN TaskActualHours Float;--Done
ALTER TABLE dbo.PMMTasks ALTER COLUMN TaskEstimatedHours Float;--Done
ALTER TABLE dbo.SVCRequests ALTER COLUMN ActualHours Float;--Done
ALTER TABLE dbo.SVCRequests ALTER COLUMN EstimatedHours Float;--Done
ALTER TABLE dbo.PMMTasksHistory ALTER COLUMN EstimatedRemainingHours Float;--Done
ALTER TABLE dbo.PMMTasksHistory ALTER COLUMN TaskActualHours Float;--Done
ALTER TABLE dbo.PMMTasksHistory ALTER COLUMN TaskEstimatedHours Float;--Done
ALTER TABLE dbo.PRS ALTER COLUMN ActualHours Float;--Done
ALTER TABLE dbo.PRS ALTER COLUMN EstimatedHours Float;--Done
ALTER TABLE dbo.Relationship ALTER COLUMN TaskActualHours Float;--Done
ALTER TABLE dbo.Relationship ALTER COLUMN TaskEstimatedHours Float;--Done
ALTER TABLE dbo.Config_Service_ServiceRelationships ALTER COLUMN TaskEstimatedHours Float;--Done
ALTER TABLE dbo.NPRResources ALTER COLUMN EstimatedHours Float;--Done
ALTER TABLE dbo.BTS_Archive ALTER COLUMN ActualHours Float;--Done
ALTER TABLE dbo.BTS_Archive ALTER COLUMN EstimatedHours Float;--Done
ALTER TABLE dbo.CRMProject ALTER COLUMN ActualLabourHours Float;--Done
ALTER TABLE dbo.CRMProject ALTER COLUMN PlannedLabourHours Float;--Done
ALTER TABLE dbo.NPRTasks ALTER COLUMN TaskEstimatedHours Float;--Done
ALTER TABLE dbo.ACR_Archive ALTER COLUMN ActualHours Float;--Done
ALTER TABLE dbo.ACR_Archive ALTER COLUMN BAAnalysisHours Float;--Done
ALTER TABLE dbo.ACR_Archive ALTER COLUMN BATestingHours Float;--Done
ALTER TABLE dbo.ACR_Archive ALTER COLUMN BATotalHours Float;--Done
ALTER TABLE dbo.ACR_Archive ALTER COLUMN DeveloperCodingHours Float;--Done
ALTER TABLE dbo.ACR_Archive ALTER COLUMN DeveloperSupportHours Float;--Done
ALTER TABLE dbo.ACR_Archive ALTER COLUMN DeveloperTotalHours Float;--Done
ALTER TABLE dbo.ACR_Archive ALTER COLUMN EstimatedHours Float;--Done
ALTER TABLE dbo.ACR_Archive ALTER COLUMN TestingTotalHours Float;--Done
ALTER TABLE dbo.ACR_Archive ALTER COLUMN TotalHours Float;--Done
ALTER TABLE dbo.INC_Archive ALTER COLUMN ActualHours Float;--Done
ALTER TABLE dbo.INC_Archive ALTER COLUMN OutageHours Float;--Done
ALTER TABLE dbo.ACR ALTER COLUMN ActualHours Float;--Done
ALTER TABLE dbo.ACR ALTER COLUMN BAAnalysisHours Float;--Done
ALTER TABLE dbo.ACR ALTER COLUMN BATestingHours Float;--Done
ALTER TABLE dbo.ACR ALTER COLUMN BATotalHours Float;--Done
ALTER TABLE dbo.ACR ALTER COLUMN DeveloperCodingHours Float;--Done
ALTER TABLE dbo.ACR ALTER COLUMN DeveloperSupportHours Float;--Done
ALTER TABLE dbo.ACR ALTER COLUMN DeveloperTotalHours Float;--Done
ALTER TABLE dbo.ACR ALTER COLUMN EstimatedHours Float;--Done
ALTER TABLE dbo.ACR ALTER COLUMN TestingTotalHours Float;--Done
ALTER TABLE dbo.ACR ALTER COLUMN TotalHours Float;--Done
ALTER TABLE dbo.ACR ALTER COLUMN TotalActualHours Float;--Done
ALTER TABLE dbo.SVCRequests_Archive ALTER COLUMN ActualHours Float;--Done
ALTER TABLE dbo.SVCRequests_Archive ALTER COLUMN EstimatedHours Float;--Done
ALTER TABLE dbo.CRMProject_Archive ALTER COLUMN ActualLabourHours Float;--Done
ALTER TABLE dbo.CRMProject_Archive ALTER COLUMN PlannedLabourHours Float;--Done
ALTER TABLE dbo.DRQ ALTER COLUMN ActualHours Float;--Done
ALTER TABLE dbo.DRQ ALTER COLUMN EstimatedHours Float;--Done
ALTER TABLE dbo.DRQ ALTER COLUMN OutageHours Float;--Done
ALTER TABLE dbo.TSK_Archive ALTER COLUMN EstimatedHours Float;--Done
ALTER TABLE dbo.TSK_Archive ALTER COLUMN EstimatedRemainingHours Float;--Done
ALTER TABLE dbo.TSK_Archive ALTER COLUMN ActualHours Float;--Done
ALTER TABLE dbo.BTS ALTER COLUMN ActualHours Float;--Done
ALTER TABLE dbo.BTS ALTER COLUMN EstimatedHours Float;--Done
ALTER TABLE dbo.Contracts ALTER COLUMN EstimatedHours Float;--Done
ALTER TABLE dbo.Contracts ALTER COLUMN ActualHours Float;--Done
ALTER TABLE dbo.CRMServices ALTER COLUMN ActualLabourHours Float;--Done
ALTER TABLE dbo.CRMServices ALTER COLUMN PlannedLabourHours Float;--Done
ALTER TABLE dbo.PMMHistory ALTER COLUMN EstimatedHours Float;--Done
ALTER TABLE dbo.PMMHistory ALTER COLUMN EstimatedRemainingHours Float;--Done
ALTER TABLE dbo.PMMHistory ALTER COLUMN TotalActualHours Float;--Done
ALTER TABLE dbo.TSKTasks ALTER COLUMN EstimatedRemainingHours Float;--Done
ALTER TABLE dbo.TSKTasks ALTER COLUMN TaskActualHours Float;--Done
ALTER TABLE dbo.TSKTasks ALTER COLUMN TaskEstimatedHours Float;--Done
ALTER TABLE dbo.ModuleTasksHistory ALTER COLUMN ActualHours Float;--Done
ALTER TABLE dbo.ModuleTasksHistory ALTER COLUMN EstimatedRemainingHours Float;--Done
ALTER TABLE dbo.ModuleTasksHistory ALTER COLUMN EstimatedHours Float;--Done
ALTER TABLE dbo.CRMServices_Archive ALTER COLUMN ActualLabourHours Float;--Done
ALTER TABLE dbo.CRMServices_Archive ALTER COLUMN PlannedLabourHours Float;--Done
ALTER TABLE dbo.PmmProjectHistory ALTER COLUMN EstimatedHours Float;--Done
ALTER TABLE dbo.PmmProjectHistory ALTER COLUMN EstimatedRemainingHours Float;--Done
ALTER TABLE dbo.PmmProjectHistory ALTER COLUMN TotalActualHours Float;--Done
ALTER TABLE dbo.UPR ALTER COLUMN ActualHours Float;--Done
ALTER TABLE dbo.UPR ALTER COLUMN EstimatedHours Float;--Done
ALTER TABLE dbo.RCA_Archive ALTER COLUMN ActualHours Float;--Done
ALTER TABLE dbo.PRS_Archive ALTER COLUMN ActualHours Float;--Done
ALTER TABLE dbo.PRS_Archive ALTER COLUMN EstimatedHours Float;--Done
ALTER TABLE dbo.PMM ALTER COLUMN EstimatedHours Float;--Done
ALTER TABLE dbo.PMM ALTER COLUMN EstimatedRemainingHours Float;--Done
ALTER TABLE dbo.PMM ALTER COLUMN TotalActualHours Float;--Done
ALTER TABLE dbo.UPR_Archive ALTER COLUMN ActualHours Float;--Done
ALTER TABLE dbo.UPR_Archive ALTER COLUMN EstimatedHours Float;--Done
ALTER TABLE dbo.TSR ALTER COLUMN ActualHours Float;--Done
ALTER TABLE dbo.TSR ALTER COLUMN EstimatedHours Float;--Done
ALTER TABLE dbo.TSR ALTER COLUMN AfterHours Float;--Done
ALTER TABLE dbo.TSR ALTER COLUMN TotalActualHours Float;--Done
ALTER TABLE dbo.TSR_Archive ALTER COLUMN ActualHours Float;--Done
ALTER TABLE dbo.TSR_Archive ALTER COLUMN EstimatedHours Float;--Done
ALTER TABLE dbo.TSR_Archive ALTER COLUMN AfterHours Float;--Done
ALTER TABLE dbo.ModuleStageConstraints ALTER COLUMN TaskActualHours Float;--Done
ALTER TABLE dbo.ModuleStageConstraints ALTER COLUMN TaskEstimatedHours Float;--Done
ALTER TABLE dbo.VCCRequest ALTER COLUMN ActualHours Float;--Done
ALTER TABLE dbo.VCCRequest ALTER COLUMN EstimatedHours Float;--Done

/*For Pct Complete*/

ALTER TABLE dbo.Opportunity ALTER COLUMN PctComplete Float;
ALTER TABLE dbo.VendorSOWInvoices ALTER COLUMN PctComplete Float;
ALTER TABLE dbo.TSK ALTER COLUMN PctComplete Float;
ALTER TABLE dbo.VendorVPM ALTER COLUMN PctComplete Float;
ALTER TABLE dbo.RCA ALTER COLUMN PctComplete Float;
ALTER TABLE dbo.VendorMSA ALTER COLUMN PctComplete Float;
ALTER TABLE dbo.Contracts_Archive ALTER COLUMN PctComplete Float;
ALTER TABLE dbo.PMM_Archive ALTER COLUMN PctComplete Float;
ALTER TABLE dbo.Lead_Archive ALTER COLUMN PctComplete Float;
ALTER TABLE dbo.Opportunity_Archive ALTER COLUMN PctComplete Float;
ALTER TABLE dbo.SVCRequests ALTER COLUMN PctComplete Float;
ALTER TABLE dbo.CRMCompany ALTER COLUMN PctComplete Float;
ALTER TABLE dbo.PRS ALTER COLUMN PctComplete Float;
ALTER TABLE dbo.CRMCompany_Archive ALTER COLUMN PctComplete Float;
ALTER TABLE dbo.CRMContact ALTER COLUMN PctComplete Float;
ALTER TABLE dbo.CRMContact_Archive ALTER COLUMN PctComplete Float;
ALTER TABLE dbo.CRMProject ALTER COLUMN PctComplete Float;
ALTER TABLE dbo.ACR_Archive ALTER COLUMN PctComplete Float;
ALTER TABLE dbo.ACR ALTER COLUMN PctComplete Float;
ALTER TABLE dbo.SVCRequests_Archive ALTER COLUMN PctComplete Float;
ALTER TABLE dbo.VendorSLA ALTER COLUMN PctComplete Float;
ALTER TABLE dbo.CRMProject_Archive ALTER COLUMN PctComplete Float;
ALTER TABLE dbo.TSK_Archive ALTER COLUMN PctComplete Float;
ALTER TABLE dbo.Contracts ALTER COLUMN PctComplete Float;
ALTER TABLE dbo.PLCRequest ALTER COLUMN PctComplete Float;
ALTER TABLE dbo.CRMServices ALTER COLUMN PctComplete Float;
ALTER TABLE dbo.PMMHistory ALTER COLUMN PctComplete Float;
ALTER TABLE dbo.CRMServices_Archive ALTER COLUMN PctComplete Float;
ALTER TABLE dbo.PmmProjectHistory ALTER COLUMN PctComplete Float;
ALTER TABLE dbo.Lead ALTER COLUMN PctComplete Float;
ALTER TABLE dbo.VendorSOW ALTER COLUMN PctComplete Float;
ALTER TABLE dbo.Investors ALTER COLUMN PctComplete Float;
ALTER TABLE dbo.UPR ALTER COLUMN PctComplete Float;
ALTER TABLE dbo.RCA_Archive ALTER COLUMN PctComplete Float;
ALTER TABLE dbo.PRS_Archive ALTER COLUMN PctComplete Float;
ALTER TABLE dbo.PMM ALTER COLUMN PctComplete Float;
ALTER TABLE dbo.Customers ALTER COLUMN PctComplete Float;
ALTER TABLE dbo.UPR_Archive ALTER COLUMN PctComplete Float;
ALTER TABLE dbo.TSR ALTER COLUMN PctComplete Float;
ALTER TABLE dbo.TSR_Archive ALTER COLUMN PctComplete Float;
ALTER TABLE dbo.VCCRequest ALTER COLUMN PctComplete Float;